<h1 align="center" style="color:orange;"> Linear Algebra </h1>

In [1]:
import numpy as np
from math import inf
from scipy.sparse import csr_matrix

### Vector norms

In [2]:
a0 = np.array((1, 2, 3, 4, 5, 6, 7))
l1 = np.linalg.norm(a0, 1)
print('L1 norm : ', l1)

l2 = np.linalg.norm(a0)
print('L2 norm : ', l2)

l_inf = np.linalg.norm(a0, math.inf)
print('L max norm : ', l_inf)

L1 norm :  28.0
L2 norm :  11.832159566199232
L max norm :  7.0


### Matrices

In [15]:
a1 = np.arange(1, 17).reshape((4, 4))
print("Original matrix (a1) : \n", a1)

# transpose
print("\nTranspose fo the matrix : \n", a1.T)

# determinant
determinant = np.linalg.det(a1)
print(f"\nDeterminant of \n{a1}\n={determinant}")

# trace
print("\nTrace of matrix : ", a1.trace())

# rank 
print("\nRank of the matrix : ", np.linalg.matrix_rank(a1))

# inverse
print("\nInverse of the matrix : ", np.linalg.inv(a1))

# eigen value, eigen vector
eigen_value, eigen_vector = np.linalg.eig(a1)
print(f'\nEigen value : {eigen_value}\n\nEigen vector : {eigen_vector}')

# Sparse matrix
a2 = np.array([
    [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
])

sparse_matrix = csr_matrix(a2)
dense_matrix = sparse_matrix.todense()

print(f'\n\nOriginal matrix : \n{a2}\n\nSparse matrix : \n{sparse_matrix}\n\nDense matrix : \n{dense_matrix}')

sparsity_score = 1 - np.count_nonzero(a2) / a2.size
print(f'\nSparsity score : {sparsity_score} or {sparsity_score*100} %')

Original matrix (a1) : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose fo the matrix : 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Determinant of 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
=4.7331654313261276e-30

Trace of matrix :  34

Rank of the matrix :  2

Inverse of the matrix :  [[ 3.94064967e+15 -4.50359963e+15 -2.81474977e+15  3.37769972e+15]
 [-4.12829966e+15  4.50359963e+15  3.37769972e+15 -3.75299969e+15]
 [-3.56534971e+15  4.50359963e+15  1.68884986e+15 -2.62709978e+15]
 [ 3.75299969e+15 -4.50359963e+15 -2.25179981e+15  3.00239975e+15]]

Eigen value : [ 3.62093727e+01 -2.20937271e+00  2.80575969e-16 -8.29646454e-16]

Eigen vector : [[-0.15115432 -0.72704996 -0.01128698 -0.250341  ]
 [-0.34923733 -0.28320876  0.42321091  0.69689908]
 [-0.54732033  0.16063243 -0.81256087 -0.64277516]
 [-0.74540333  0.60447363  0.40063694  0.19621708]]


Original matrix : 
[[0 0 1 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 

### Tensor Operations

In [14]:
# tensor dot product
# a3 = np.arange(1, 25).reshape(2, 4, 3)
# a4 = np.arange(25, 49).reshape(2, 4, 3)

# tensor_dot_prod = np.tensordot(a3, a4, axes=0)
# print(f'Tensor dot product of a3\n{a3}\nand a4\n{a4}\nis\n{tensor_dot_prod}')

a5 = np.array((2, 5))
a6 = np.array((1, 3))

tensor_dot_product = np.tensordot(a5, a6, axes=0)
print(f'\nTensor dot product of a3 : {a5} and a4 {a6} is\n{tensor_dot_product}')

Original matrix : 
[[0 0 1 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 1]]

Sparse matrix : 
  (0, 2)	1
  (0, 7)	1
  (1, 0)	1
  (1, 4)	1
  (2, 0)	1
  (2, 9)	1
  (3, 0)	1
  (3, 1)	1
  (3, 9)	1

Dense matrix : 
[[0 0 1 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 1]]

Sparsity score : 0.775 or 77.5 %

Tensor dot product of a3 : [2 5] and a4 [1 3] is
[[ 2  6]
 [ 5 15]]


In [23]:
# solve matrix (system of linear equation)
a7 = np.arange(1, 10).reshape((3, 3))
a8 = np.arange(11, 20).reshape((3, 3))

a9 = np.linalg.solve(a7, a8)

print("Solution : ", a9)
print('\nIs the solution correct : ', np.allclose(np.dot(a7, a9), a8))

# inner product
a10 = np.array([[1], [2], [3]])
a11 = np.array([[-1], [2], [5]])

print(f'\nInner product : {np.dot(np.transpose(a10), a11)}')

Solution :  [[-17. -18. -27.]
 [ 26.  27.  44.]
 [ -8.  -8. -16.]]

Is the solution correct :  True

Inner product : [[18]]
