<h1 align="center" style="color:orange;"> Linear Algebra </h1>


### Topics

- Determinant of a matrix
- Solving linear matrix equation, or system of linear scalar equations
- Row and column vectors
- Inner product of two vectors
- Matrix multiplication

In [3]:
import numpy as np

In [6]:
# determinant of a given matrix

x = np.array([
    [1, 2, 1],
    [0, 3, 5], 
    [4, 3, 8]
  ])

det_x = np.linalg.det(x)

print(f'{x} \nDeterminant of the matrix = {det_x:.2f}')

[[1 2 1]
 [0 3 5]
 [4 3 8]] 
Determinant of the matrix = 37.00


In [25]:
# Solve a linear matrix equation, or system of linear scalar equations.

A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print(f"Matrix A :\n{A}\n\nArray b :\n{b}")

Matrix A :
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b :
[-10.   0.  17.]


In [13]:
# checking the shape of the matrix
print(f"A :{np.shape(A)}\nB :{np.shape(b)}")

# solution
print(f'Solution: {np.linalg.solve(A, b)}')

A :(3, 3)
B :(3,)
Solution: [ 1.  4. -2.]


In [14]:
# Row vector and Column vector

row_vec = np.array([1, 2, 3, 4, 5])
col_vec = np.array([[1], [2], [3], [4], [5]])

print(row_vec, col_vec, sep='\n\n')

[1 2 3 4 5]

[[1]
 [2]
 [3]
 [4]
 [5]]


In [24]:
# inner product
x = np.array([[1], [2], [3]])
y = np.array([[-1], [2], [5]])

print(f'Inner product : {np.dot(np.transpose(x), y)}')

Inner product : [[18]]


In [22]:
# matrix multiplication

mat1 = np.arange(1, 13).reshape(3, 4)
mat2 = np.arange(12, 24).reshape(4, 3)

print(f"Matrix 1 :\n{mat1}\n\nMatrix 2 :\n{mat2}")

print(f"\nMatrix multiplication :\n {mat1 @ mat2}")

Matrix 1 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix 2 :
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

Matrix multiplication :
 [[180 190 200]
 [444 470 496]
 [708 750 792]]


**Matrix multiplication algorithm (Brute force approach)**

``` python
    for each row i in C:
        for each col j in C:
            for k in 1 ... n:
                C[i][j] += A[i][k] * B[k][j]
```

**Time complexity of this algorithm is `O(` $N^{3}$ `)`**

In [28]:
# dot product of two matrix
print(f'Multiplication:\n {A.dot(b)}')

# Transpose
print(f'\nMatrix A:\n {A}\n')
print(f'Transpose of A :\n {np.transpose(A)}')

Multiplication:
 [-23.  31. -75.]

Matrix A:
 [[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Transpose of A :
 [[ 4.  2. -1.]
 [-3.  1.  2.]
 [ 1.  3. -5.]]


In [31]:
mat3 = np.arange(1, 10).reshape(3, 3)
print(f'Original array: \n {mat3}\n')
print(f'Trace : {mat3.trace()}')

Original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Trace : 15


In [32]:
# rank of a matrix

print(f'Original Matrix: \n {mat3}\n')
print(f'Rank of the matrix is : {np.linalg.matrix_rank(mat3)}')

Original Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank of the matrix is : 2


In [39]:
# inverse

print(f'Original Matrix: \n {mat3}\n')

print(f'Determinant of the matrix is : {np.linalg.det(mat3):.0f}')

print(f'\nInverse of the matrix is : \n {np.linalg.inv(mat3)}')

Original Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of the matrix is : 0

Inverse of the matrix is : 
 [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


In [42]:
# eigen value and eigen vectors

print(f'Original Matrix: \n {mat3}\n')

value, vector = np.linalg.eig(mat3)

print(f'Eigenvalue :\n {value}\n')
print(f'Eigenvectors :\n {vector}')
print(f'\nTrace of the vector: {mat3.trace()}')

Original Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Eigenvalue :
 [ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]

Eigenvectors :
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

Trace of the vector: 15


<h1 align="center" style="color:orange;"> Combinatorics </h1>

In [43]:
from itertools import permutations, combinations

In [48]:
# How many combinations of 2 subjects from the list

subjects = ( 'Python', 'Biology', 'Mathematics', 'Physics' )
arrangements = list(permutations(subjects, 3))
print(f"permutations : {arrangements}\n\n Count : {len(arrangements)}")

permutations : [('Python', 'Biology', 'Mathematics'), ('Python', 'Biology', 'Physics'), ('Python', 'Mathematics', 'Biology'), ('Python', 'Mathematics', 'Physics'), ('Python', 'Physics', 'Biology'), ('Python', 'Physics', 'Mathematics'), ('Biology', 'Python', 'Mathematics'), ('Biology', 'Python', 'Physics'), ('Biology', 'Mathematics', 'Python'), ('Biology', 'Mathematics', 'Physics'), ('Biology', 'Physics', 'Python'), ('Biology', 'Physics', 'Mathematics'), ('Mathematics', 'Python', 'Biology'), ('Mathematics', 'Python', 'Physics'), ('Mathematics', 'Biology', 'Python'), ('Mathematics', 'Biology', 'Physics'), ('Mathematics', 'Physics', 'Python'), ('Mathematics', 'Physics', 'Biology'), ('Physics', 'Python', 'Biology'), ('Physics', 'Python', 'Mathematics'), ('Physics', 'Biology', 'Python'), ('Physics', 'Biology', 'Mathematics'), ('Physics', 'Mathematics', 'Python'), ('Physics', 'Mathematics', 'Biology')]

 Count : 24


In [49]:
comb = list(combinations(subjects, 3))
print(f'combinations : {comb}\n\nCount : {len(comb)}')

combinations : [('Python', 'Biology', 'Mathematics'), ('Python', 'Biology', 'Physics'), ('Python', 'Mathematics', 'Physics'), ('Biology', 'Mathematics', 'Physics')]

Count : 4


In [54]:
# factorial 
from scipy.special import factorial


print(f'factorial of 10 : {factorial(10)}')
n = 26
k = 8
print(factorial(n)/factorial(n-k))

factorial of 10 : 3628800.0
62990928000.000015
