<h1 align="center" style="color:orange;"> Linear Algebra </h1>

In [1]:
# importing dependencies/libraries

import numpy as np

<h2  style="color:orange;">

System of Linear Equations

</h2>

A system of linear equations is a collection of linear equations involving the same set of variables. For example, the following system of linear equations:

$$\begin{align} 2x + 3y &= 8 \\ 3x + 4y &= 9 \end{align}$$ 

is a system of two equations in the variables $x$ and $y$.

A solution to a system of linear equations is a set of values for the variables that satisfies all the equations simultaneously. For example, the values $x = 1$ and $y = 2$ is a solution to the system above.

A system of linear equations can have either no solution, a unique solution or infinitely many solutions. For example, 

- The system of equations:

$$\begin{align} 2x + 3y &= 8 \\ 4x + 6y &= 9 \end{align}$$

has **no solution**. 

- The system of equations:

$$\begin{align} 2x + 3y &= 8 \\ 4x + 6y &= 16 \end{align}$$

has **infinitely many solutions**. 

- The system of equations:

$$\begin{align} 2x + 3y &= 8 \\ 4x + 6y &= 20 \end{align}$$

has a **unique solution**.

<h2  style="color:orange;">

Matrix Representation of a System of Linear Equations

</h2>

A system of linear equations can be represented in the matrix form as follows:

$$\begin{bmatrix} 2 & 3 \\ 3 & 4 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 8 \\ 9 \end{bmatrix}$$

where the matrix on the left is called the **coefficient matrix** and the matrix on the right is called the **augmented matrix**.


### Questions
1. Bob has a mixture of apples and oranges of the same size, which he split into two bags. The first bag contains 4 apples and 3 oranges and weighs 700g. The second bag contains 2 apples and 6 oranges and weighs 1000g. 

  Translate the following description into a system of linear equations.

**Ans**: $4a + 3o = 700$ and $2a + 6o = 1000$

2. Translate the following system of linear equations into the matrix form:

$$5x+3y+5z=6\\7x+2y+8z=17\\4x+3z=8$$

**Ans**: $ \begin{bmatrix} 5 & 3 & 5 &\\ 7 & 2 & 8 \\ 0 & 4 & 3 \end{bmatrix} \hspace{1em} \begin{bmatrix}  x\\y\\z \end{bmatrix} \hspace{1em}=\hspace{1em} \begin{bmatrix} 6 \\ 17 \\ 8\end{bmatrix}$



3. Compute the determinant of the following matrix.

```py
  X = [
    [1, 2, 1],
    [0, 3, 5], 
    [4, 3, 8]
  ]
```

In [2]:
x = np.array([
    [1, 2, 1],
    [0, 3, 5], 
    [4, 3, 8]
  ])

det_x = np.linalg.det(x)

print(f'Determinant of the matrix:\n {x} = {det_x:.2f}')

Determinant of the matrix:
 [[1 2 1]
 [0 3 5]
 [4 3 8]] = 37.00


<h2  style="color:orange;">

Determinant of a matrix

</h2>

Determinant of a matrix is a special value which tells us whether the matrix has an inverse or not. It is denoted by $$det(X) \;or \;|X|$$ It is a scalar value and helps in solving systems of linear equations.

**Calculating the determinant of a 2x2 matrix** : $det(X) = ad-bc$ where; 
$$ X= \begin{bmatrix} a & b \\ c & d\end{bmatrix}$$

> For a larger matrix we can find the determinant using a process called Co-factor expansion; which involves choosing a row or column and calculating the determinants of smaller matrices called cofactors. This process can be recursive, meaning you keep calculating determinants of smaller matrices until you reach a 2x2 matrix that you can solve using the formula above

**Note**

- All matrices does not have a determinant. Only square matrices have determinant. 

- If the determinant is zero, the matrix is said to be singular, and it does not have an inverse. 

we can use the following `numpy` function to calculate the determinant of a matrix.

```py
numpy.linalg.det() 
```


Consider the following matrix

$$\begin{bmatrix}  a & b \\ c & d\end{bmatrix}$$

The given matrix is singular if $a * b * k$ = $c * d$

or; $$a*k = c \hspace{1em} and \hspace{1em}b*k = d$$

or; $$\frac{c}{a}=\frac{d}{b} = k$$

$$ad = bc$$

$$ad-bc = 0$$ 

This value of $ad-bc = 0$ is important, we call it the determinant of the matrix.


<h2  style="color:orange;">

Slope 

</h2>

Slope is a measure of how steep a line is. It is defined as the change in the `y-coordinate` (vertical change) divided by the change in the `x-coordinate` (horizontal change) between any two points on the line. 
$$Slope = \frac{rise}{run}$$

**In simple terms it tells us how many units the line moves down for every unit we moves to the right**

### Note

- If a system of linear equations has a unique solution; then they are complete and non-singular.

- If a system of linear equation has infinite solutions; it is redundant and singular.

- if the system of linear equation has no solution; it is called Contradictory and singular.

The constants in the system of equation are not important in determining whether the system is singular or not.



<h3  style="color:orange;">

Matrix row reduction or Gaussian elimination

</h3>

Matrix row reduction also known as Gaussian elimination is a method used to solve a system of linear equations. It involves transforming the augmented matrix into a matrix in `row echelon form` and then into `reduced row echelon form` using elementary row operations. In simple terms we are trying to transform the augmented matrix into a matrix that is easier to solve.

**Row echelon form** is a matrix where all the elements below the main diagonal are zero. Generally, the main diagonal contains a bunch of ones followed by perhaps some zeros, it can be al ones or all zeros.

$$\begin{bmatrix}  1 & * & * & *\\ 0 & 1 & * & * \\ 0 & 0 & 0 & * \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

**Row Operations**

- Interchange two rows : $R_i \leftrightarrow R_j$ 

Interchanging two rows of a matrix is equivalent to multiplying the matrix by a permutation matrix. It won't change the determinant of the matrix. If the original matrix was singular, the new matrix will also be singular. The determinant of the new matrix will be the same as the determinant of the original matrix but sign will change(as diagonal elements are interchanged).
> A permutation matrix is a square matrix obtained from the identity matrix by permuting its rows.

- Multiplying the a row by a non-zero scalar : $kR_i \rightarrow R_i$

This would also not change the determinant of the matrix, it would scale the determinant by a factor of $k$.
>For example if $k = 2$ then the determinant would be scaled by a factor of 2.

- Adding a row to another row : $R_i + R_j \rightarrow R_i$

This operation also preserves the determinant of the matrix.



In [4]:
# matrix A
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

# array b
b = np.array([-10, 0, 17], dtype=np.dtype(float))

In [5]:
# checking the shape of the matrix
print(f'Shape of the matrix A is : {np.shape(A)}')
print(f'Shape of the array b is : {np.shape(b)}')

Shape of the matrix A is : (3, 3)
Shape of the array b is : (3,)


In [6]:
# solution to the system of equations represented as matrix
print(f'Solution: {np.linalg.solve(A, b)}')

Solution: [ 1.  4. -2.]
