<h1 align="center" style="color:orange;"> Linear Algebra </h1>

In [1]:
import numpy as np
from scipy import linalg

### Solving systems of linear equations

In [ ]:
# Generate example system: Ax = b
A = np.array([[3, 2], [1, 2]])
b = np.array([7, 5])
print(f"A:\n{A}\n\nB:\n{b}")

# Method 1: Direct solve (uses LU decomposition internally)
x_direct = np.linalg.solve(A, b)
print(f"\nDirect solution: {x_direct}")
# Output: [1. 2.]

# Method 2: Least squares (handles overdetermined systems)
A_over = np.array([[3, 2], [1, 2], [2, 1]])  # 3 equations, 2 unknowns
b_over = np.array([7, 5, 4])
x_lstsq = np.linalg.lstsq(A_over, b_over, rcond=None)[0]
print(f"\nLeast squares solution: {x_lstsq}")

# Method 3: Using QR decomposition explicitly
Q, R = np.linalg.qr(A)
x_qr = linalg.solve_triangular(R, Q.T @ b)
print(f"\nQR solution: {x_qr}")

# Method 4: Check solution validity
residual = np.linalg.norm(A @ x_direct - b)
print(f"\nResidual: {residual:.2e}")  # Should be ~0 for exact solution

A:
[[3 2]
 [1 2]]

B:
[7 5]

Direct solution: [1. 2.]

Least squares solution: [1. 2.]

QR solution: [1. 2.]

Residual: 0.00e+00


### Vector Arithmetic

In [12]:
# vector
vector_1 = np.array([1, 2, 3])
vector_2 = np.array([4, 5, 6])

# add vectors
vector_3 = vector_1 +  vector_2

# subtract two vectors
vector_4 = vector_1 - vector_2

# multiply vectors
vector_5 = vector_1 * vector_2

# divide vector
vector_6 = vector_2 / vector_1

# vector dot product
vector_7 = vector_1.dot(vector_2)

# vector scalar multiplication
vector_8 = vector_1 * 0.5

print("Given two vectors are : ", vector_1, vector_2)
print(f"\nVector Addition : {vector_1} + {vector_2} = {vector_3}")
print(f"\nVector Subtraction : {vector_1} - {vector_2} = {vector_4}")
print(f"\nVector Multiplication : {vector_1} * {vector_2} = {vector_5}")
print(f"\nVector Division : {vector_2} / {vector_1} = {vector_6}")
print(f"\nVector Dot product : {vector_1} . {vector_2} = {vector_7}")
print(f"\nVector Scalar multiplication : {vector_1} * 0.5 = {vector_8}")

Given two vectors are :  [1 2 3] [4 5 6]

Vector Addition : [1 2 3] + [4 5 6] = [5 7 9]

Vector Subtraction : [1 2 3] - [4 5 6] = [-3 -3 -3]

Vector Multiplication : [1 2 3] * [4 5 6] = [ 4 10 18]

Vector Division : [4 5 6] / [1 2 3] = [4.  2.5 2. ]

Vector Dot product : [1 2 3] . [4 5 6] = 32

Vector Scalar multiplication : [1 2 3] * 0.5 = [0.5 1.  1.5]


### Vector norms

In [11]:
vec_9 = np.array([-1, 2, 3, -4, 5, -6, 7])

# norm order parameter = 1
l1_norm = np.linalg.norm(vec_9, 1)

# norm order = default
l2_norm = np.linalg.norm(vec_9)

# norm order = inf
l_inf_norm = np.linalg.norm(vec_9, float('inf'))

print('L1 norm : ', l1_norm)
print('L2 norm : ', l2_norm)
print('L max norm : ', l_inf_norm)

L1 norm :  28.0
L2 norm :  11.832159566199232
L max norm :  7.0


### Matrix Operations

```python
# matrix addition
def add_matrices(A: list[list[int]], B: list[list[int]]) -> list[list[int]]:
    """Add two matrices with same dimension"""
    
    # Check for valid matrices.
    #TODO: This is not exhaustive, complete this
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        raise ValueError("Matrices must have the same dimension")
    
    res = [[0 for _ in range(len(A[0]))] for _ in range(len(A))]

    # Add corresponding elements
    for i in range(len(A)):
        for j in range(len(A[0])):
            res[i][j] = A[i][j] + B[i][j]
    return res
```


```python
# matrix subtraction
def subtract_matrices(A: list[list[int]], B: list[list[int]]) -> list[list[int]]:
    """Subtract two matrices with same dimension"""
    
    # Check for valid matrices.

    if len(A) != len(B) or len(A[0]) != len(B[0]):
        raise ValueError("Matrices must have the same dimension")
        
    res = [[0 for _ in range(len(A[0]))] for _ in range(len(A))]

    # Subtract corresponding elements

    for i in range(len(A)):
        for j in range(len(A[0])):
            res[i][j] = A[i][j] - B[i][j]

    return res
```

```python
# matrix multiplication
def multiply_matrices(A: list[list[int]], B: list[list[int]]) -> list[list[int]]:
    """Multiply two matrices"""
    
    # Check for valid matrices.

    if len(A[0]) != len(B):
        raise ValueError("Number of columns in A must be equal to number of rows in B")
        
    res = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

    # Multiply corresponding elements

    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                res[i][j] += A[i][k] * B[k][j]

    return res
```

In [13]:
# Using numpy
A = np.array([
    [1, -2, 3, -4],
    [-9, 8, -7, 6],
    [13, 0, -7, 5]
])

B = np.arange(1, 13).reshape((3, 4))

# add two matrices
C = A + B

# subtract two matrices
D = A - B

# Hadamard product or element-wise matrix multiplication
E = A * B

# Matrix - Matrix multiplication or matrix dot product
F = np.arange(10, 18).reshape((4, 2))
G = A @ F # A.dot(F)

# Matrix division
H = A / B

print("A : ", A, "\nB : ", B, sep='\n')
print("\nA + B = ", C, sep='\n')
print("\nA - B = ", D, sep='\n')
print("\nElement-wise matrix multiplication: A o B = ", E, sep='\n')
print("\n Matrix F: ", F)
print("\nMatrix dot product: A . F = ", G, sep='\n')
print("\nA / F = ", H, sep='\n')

A : 
[[ 1 -2  3 -4]
 [-9  8 -7  6]
 [13  0 -7  5]]

B : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

A + B = 
[[ 2  0  6  0]
 [-4 14  0 14]
 [22 10  4 17]]

A - B = 
[[  0  -4   0  -8]
 [-14   2 -14  -2]
 [  4 -10 -18  -7]]

Element-wise matrix multiplication: A o B = 
[[  1  -4   9 -16]
 [-45  48 -49  48]
 [117   0 -77  60]]

 Matrix F:  [[10 11]
 [12 13]
 [14 15]
 [16 17]]

Matrix dot product: A . F = 
[[-36 -38]
 [  4   2]
 [112 123]]

A / F = 
[[ 1.         -1.          1.         -1.        ]
 [-1.8         1.33333333 -1.          0.75      ]
 [ 1.44444444  0.         -0.63636364  0.41666667]]


### Properties of Matrices

In [3]:
# Transpose of a matrix
J = np.arange(1, 13).reshape((3, 4))
J_transpose = J.T

# Inverse of a matrix
K = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [0, 0, 1]])
K_inv = np.linalg.inv(K)

# trace of a matrix
K_trace = np.trace(K)

# determinant of a matrix
K_det = np.linalg.det(K)

# Rank of a matrix
K_rank = np.linalg.matrix_rank(K)
vector_rank = np.linalg.matrix_rank(K[0])
L = np.array([
    [0, 0],
    [0, 0]
])
M = np.array([
    [1, 2],
    [1, 2]
])
N = np.array([
    [1, 2],
    [3, 4]
])

print("Matrix J is : ", J, sep='\n')
print("\nTranspose of a Matrix J is : ", J_transpose, sep='\n')
print("\nThe matrix K is : ", K, sep='\n')
print("\nInverse of Matrix K is : ", K_inv, sep='\n')
print("\nK . K_inv gives identity matrix : ", K.dot(K_inv), sep='\n')
print("\nTrace of matrix K is : ", K_trace, sep='\n')
print("\nDeterminant of matrix K is : ", K_det, sep='\n')
print("\nRank of matrix K is : ", K_rank, sep='\n')
print(f"\nRank of matrix vector {K[0]} is:\n{vector_rank} ")
print(f"\nThree two dimensional vector with different value ->\n{L}\n\n{M}\n\n{N}")
print(f"\nRank of L : {np.linalg.matrix_rank(L)}\nRank of M : {np.linalg.matrix_rank(M)}\nRank of N : {np.linalg.matrix_rank(N)}")

Matrix J is : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose of a Matrix J is : 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

The matrix K is : 
[[1 0 1]
 [0 1 0]
 [0 0 1]]

Inverse of Matrix K is : 
[[ 1.  0. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

K . K_inv gives identity matrix : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Trace of matrix K is : 
3

Determinant of matrix K is : 
1.0

Rank of matrix K is : 
3

Rank of matrix vector [1 0 1] is:
1 

Three two dimensional vector with different value ->
[[0 0]
 [0 0]]

[[1 2]
 [1 2]]

[[1 2]
 [3 4]]

Rank of L : 0
Rank of M : 1
Rank of N : 2


### Types of Matrices

In [2]:
# triangular upper and lower matrices
I = np.arange(1, 10).reshape((3, 3))

upper_triangular = np.triu(I)
lower_triangular = np.tril(I)

# diagonal matrix from vector and extract diagonal from a matrix
diagonal_vector = np.diag(I)
diagonal_matrix = np.diag(diagonal_vector)

# Identity matrix
identity_matrix = np.identity(3, dtype=int)

# Orthogonal matrix
orth_matrix = np.array([
    [1, 0],
    [0, -1]])
inverse_matrix = np.linalg.inv(orth_matrix)

print("Upper Triangular: ", upper_triangular, sep='\n')
print("\nLower Triangular: ", lower_triangular, sep='\n')
print("\nDiagonal of Matrix I: ", diagonal_vector)
print("\nDiagonal Matrix from vector: ", diagonal_matrix, sep='\n')
print("\nIdentity Matrix : ", identity_matrix, sep='\n')
print("\nOrthogonal Matrix : ", orth_matrix, sep='\n')
print("\nInverse of orthogonal matrix : ", inverse_matrix, sep='\n')
print("\nTranspose of Orthogonal matrix (equivalent to inverse of orthogonal matrix) : ", orth_matrix.T, sep='\n')
print("\nDot product of orthogonal matrix and its transpose (Identity matrix) : ", orth_matrix.dot(orth_matrix.T), sep='\n')

Upper Triangular: 
[[1 2 3]
 [0 5 6]
 [0 0 9]]

Lower Triangular: 
[[1 0 0]
 [4 5 0]
 [7 8 9]]

Diagonal of Matrix I:  [1 5 9]

Diagonal Matrix from vector: 
[[1 0 0]
 [0 5 0]
 [0 0 9]]

Identity Matrix : 
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Orthogonal Matrix : 
[[ 1  0]
 [ 0 -1]]

Inverse of orthogonal matrix : 
[[ 1.  0.]
 [-0. -1.]]

Transpose of Orthogonal matrix (equivalent to inverse of orthogonal matrix) : 
[[ 1  0]
 [ 0 -1]]

Dot product of orthogonal matrix and its transpose (Identity matrix) : 
[[1 0]
 [0 1]]


In [11]:
# sparse matrices
from scipy.sparse import csr_matrix


P = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 1]
])

P_sparse = csr_matrix(P)
sparsity_score = 1.0 - np.count_nonzero(P) / P.size

print("Given matrix P : ", P, sep='\n')
print("\nSparse matrix : ", P_sparse, sep='\n')
print("\nSparse matrix to dense matrix : ", P_sparse.todense(), sep='\n')
print("\nSparsity score of matrix P : ", sparsity_score, "or", sparsity_score*100, "%")

Given matrix P : 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 1]]

Sparse matrix : 
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	1
  (1, 1)	1
  (3, 3)	1

Sparse matrix to dense matrix : 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 1]]

Sparsity score of matrix P :  0.8125 or 81.25 %


### Matrix Decomposition

In [20]:
# LU Decomposition
from scipy.linalg import lu

square_matrix_A = np.arange(1, 10).reshape((3, 3))
P_MATRIX, L_MATRIX, U_MATRIX = lu(square_matrix_A)
reconstruct_square_matrix_A = P_MATRIX.dot(L_MATRIX).dot(U_MATRIX)

# DR Decomposition
B_Matrix = np.array([
    [1, 2],
    [4, 5],
    [8, 9]
])
# adding the 'complete' param will ensure that Q will have size m X m and R will have size m X n
Q_matrix, R_matrix = np.linalg.qr(B_Matrix, 'complete')
reconstruct_B = Q_matrix @ R_matrix

# Cholesky Decomposition
square_definite_symmetric_matrix =  np.array([
    [3, 2, 2],
    [2, 3, 2],
    [2, 2, 3]
])
# upper=True would return the upper triangular matrix; default is False 
cholesky_matrix = np.linalg.cholesky(square_definite_symmetric_matrix)
reconstruct_from_cholesky = cholesky_matrix @ cholesky_matrix.T

# Eigendecomposition
eigenvalues, eigenvectors = np.linalg.eig(square_matrix_A)
# reconstruct matrix
inv_eigenvector = np.linalg.inv(eigenvectors)
diagonal_matrix_eigenvalues = np.diag(eigenvalues)
original_matrix = eigenvectors @ diagonal_matrix_eigenvalues @ inv_eigenvector



print(f'Original square matrix A : \n{square_matrix_A}')
print(f'\nObtained P, L, and U matrices from LU Decomposition : \np :\n{P_MATRIX} \n\nL :\n{P_MATRIX} \n\nU :\n{U_MATRIX}')
print(f'\nReconstructed matrix from P, L, U : \n{reconstruct_square_matrix_A}')

print("\n\nOriginal matrix B : \n", B_Matrix)
print("\nQ and R matrices obtained from Q R Decomposition : ", "\nQ : ", Q_matrix, "\nR : ", R_matrix, sep='\n')
print("\nReconstructed matrix from Q and R : \n", reconstruct_B)

print("\n\nOriginal Matrix A : \n", square_definite_symmetric_matrix)
print("\nCholesky matrix : \n", cholesky_matrix)
print("\nMatrix reconstructed form Cholesky matrix : \n", reconstruct_from_cholesky)

print("\n\nSquare Matrix A : \n", square_matrix_A)
print("\nEigenvalues : ", eigenvalues)
print("\nEigenvectors : \n", eigenvectors)
print("\n\nReconstruct matrix from eigenvalues and eigenvectors, Inverse of eigen vectors : \n", inv_eigenvector)
print("\n Diagonal matrix of eigen values : \n", diagonal_matrix_eigenvalues)
print("\nOriginal matrix reconstructed : \n", original_matrix)

Original square matrix A : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Obtained P, L, and U matrices from LU Decomposition : 
p :
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

L :
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

U :
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]

Reconstructed matrix from P, L, U : 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Original matrix B : 
 [[1 2]
 [4 5]
 [8 9]]

Q and R matrices obtained from Q R Decomposition : 

Q : 
[[-0.11111111 -0.87831549 -0.46499055]
 [-0.44444444 -0.37457572  0.81373347]
 [-0.88888889  0.2970773  -0.34874292]]

R : 
[[ -9.         -10.44444444]
 [  0.          -0.95581392]
 [  0.           0.        ]]

Reconstructed matrix from Q and R : 
 [[1. 2.]
 [4. 5.]
 [8. 9.]]


Original Matrix A : 
 [[3 2 2]
 [2 3 2]
 [2 2 3]]

Cholesky matrix : 
 [[1.73205081 0.         0.        ]
 [1.15470054 1.29099445 0.        ]
 [1.15470054 0.51639778 1.18321596]]

Matrix reconstructed form Cholesky matrix : 
 [

In [2]:
# SVD
from scipy.linalg import svd


W = np.array([
    [4, 2, 6],
    [5, 1, 2],
    [9, 1, 1],
    [3, 5, 7]
])
U, s, V = svd(W)

# P.Inv
pseudo_inv = np.linalg.pinv(W)

# calculating P.Inv without np.linalg.pinv()
# Reciprocal of s
reciprocal_s = 1.0 / s

zero_matrix = np.zeros(W.shape)

# s is a vector of singular values of length min(M, N) of W
# diagonal matrix of reciprocal_s would be 3 X 3 here.
# We replace the first 3 X 3 values of zero matrix with diagonal matrix
zero_matrix[0:W.shape[1], 0:W.shape[1]] = np.diag(reciprocal_s)

p_inv_new = V.T @ zero_matrix.T @ U.T

print("Given matrix W : \n", W)
print("\nU: \n", U, "\n\ns: \n", s, "\n\nV: \n", V)
print("\n\nGiven matrix W: \n", W)
print("\nPseudoInverse of W : \n", pseudo_inv)
print("\nPseudoInverse (without using np.linalg.pinv() function) of W : \n", p_inv_new)

Given matrix W : 
 [[4 2 6]
 [5 1 2]
 [9 1 1]
 [3 5 7]]

U: 
 [[-0.50621566  0.2622625   0.7924518  -0.21675846]
 [-0.36806485 -0.24457593  0.089958    0.89253484]
 [-0.53521226 -0.71543254 -0.21323546 -0.39526543]
 [-0.56729341  0.59963095 -0.56432113 -0.0127505 ]] 

s: 
 [14.10543944  7.11282752  1.56341387] 

V: 
 [[-0.7361683  -0.33690375 -0.5869856 ]
 [-0.67678145  0.36028868  0.64199606]
 [ 0.00480661 -0.86987811  0.49324332]]


Given matrix W: 
 [[4 2 6]
 [5 1 2]
 [9 1 1]
 [3 5 7]]

PseudoInverse of W : 
 [[ 0.0039018   0.04275728  0.09535035 -0.02918225]
 [-0.41554219 -0.05364981  0.09518777  0.35790928]
 [ 0.29474882  0.0216225  -0.10957568 -0.10030889]]

PseudoInverse (without using np.linalg.pinv() function) of W : 
 [[ 0.0039018   0.04275728  0.09535035 -0.02918225]
 [-0.41554219 -0.05364981  0.09518777  0.35790928]
 [ 0.29474882  0.0216225  -0.10957568 -0.10030889]]


### Tensors & Tensor Arithmetic

In [16]:
T1 = np.array([
    [[1, 2, 3, 4], [0, 9, 8, 8]],
    [[4, 5, 6, 7], [1, 0, 9, 4]],
    [[1, 9, 4, 5], [2, 5, 6, 8]]
])

print("Depth-Row-Col", T1.shape)
print("\n3D Tensor : \n", T1)

Depth-Row-Col (3, 2, 4)

3D Tensor : 
 [[[1 2 3 4]
  [0 9 8 8]]

 [[4 5 6 7]
  [1 0 9 4]]

 [[1 9 4 5]
  [2 5 6 8]]]


In [27]:
T2 = np.arange(1, 25).reshape((3, 2, 4))

# Tensor addition
T3 = T1 +  T2

# Tensor subtraction
T4 = T3 - T2

# Tensor multiplication (Hadamard product)
T5 = T1 * T2

# Tensor division
T6 = T3 / T2

# Tensor dot product
T7 = np.array([
    [1, 2, 3]
])

T8 = np.tensordot(T7, T1, axes=0)

print("Tensor T1 : \n", T1)
print("\nTensor T2 : \n", T2)
print("\nAdding tensors T1 and T2 : \n", T3)
print("\nSubtracting tensors T2 from T3 : \n", T4)
print("\nMultiplying tensors T1 from T2 : \n", T5)
print("\nDividing tensors T2 from T3 : \n", T6)
print("\nTensor dot product of T1 and T7 : \n", T8, "\n Dimension of tensor dot product is : ", T8.shape)

Tensor T1 : 
 [[[1 2 3 4]
  [0 9 8 8]]

 [[4 5 6 7]
  [1 0 9 4]]

 [[1 9 4 5]
  [2 5 6 8]]]

Tensor T2 : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]

Adding tensors T1 and T2 : 
 [[[ 2  4  6  8]
  [ 5 15 15 16]]

 [[13 15 17 19]
  [14 14 24 20]]

 [[18 27 23 25]
  [23 27 29 32]]]

Subtracting tensors T2 from T3 : 
 [[[1 2 3 4]
  [0 9 8 8]]

 [[4 5 6 7]
  [1 0 9 4]]

 [[1 9 4 5]
  [2 5 6 8]]]

Multiplying tensors T1 from T2 : 
 [[[  1   4   9  16]
  [  0  54  56  64]]

 [[ 36  50  66  84]
  [ 13   0 135  64]]

 [[ 17 162  76 100]
  [ 42 110 138 192]]]

Dividing tensors T2 from T3 : 
 [[[2.         2.         2.         2.        ]
  [1.         2.5        2.14285714 2.        ]]

 [[1.44444444 1.5        1.54545455 1.58333333]
  [1.07692308 1.         1.6        1.25      ]]

 [[1.05882353 1.5        1.21052632 1.25      ]
  [1.0952381  1.22727273 1.26086957 1.33333333]]]

Tensor dot product of T1 and T7 : 
 [[[[[ 1  2  3  4]
 

### Data Reduction using SVD

In [14]:
# Define a 5 X 25 matrix
data_matrix = np.arange(1, 126).reshape((5, 25))

# SVD
U, s, V = svd(data_matrix)

# m X n Sigma matrix
sigma = np.zeros(data_matrix.shape)

# populate sigma with n X n diagonal matrix
sigma[:data_matrix.shape[0], :data_matrix.shape[0]] = np.diag(s)

ELEMENTS = 3
# sigma[Row, Col]
sigma = sigma[:, 0:ELEMENTS]
V = V[:ELEMENTS, :]

# Reconstruct
reconstruct_data_matrix = U @ sigma @ V

# transform
transform1 = U @ sigma
transform2 = data_matrix @ V.T

In [16]:
print(f"Data matrix : \n{data_matrix}")
print(f"\n\nReconstruct Data matrix : \n{reconstruct_data_matrix}")
print(f"\n\nT1 : \n{transform1}")
print(f"\n\nT2 : \n{transform2}")

Data matrix : 
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25]
 [ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
   44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
   69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
   94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
  119 120 121 122 123 124 125]]


Reconstruct Data matrix : 
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
   15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.]
 [ 26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.
   40.  41.  42.  43.  44.  45.  46.  47.  48.  49.  50.]
 [ 51.  52.  53.  54.  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.
   65.  66.  67.  68.  69.  70.  71.  72.  73.  74.  75.]
 [ 76.  77.  78.  79.  80.  81.  82.  83

In [18]:
# Scikit learn has this builtin
from sklearn.decomposition import TruncatedSVD


trunc_svd = TruncatedSVD(n_components=3)

trunc_svd.fit(data_matrix)
out = trunc_svd.transform(data_matrix)

print(out)

[[ 6.78880492e+01 -3.02690068e+01  7.77156117e-16]
 [ 1.92414922e+02 -1.94035547e+01  3.33066907e-15]
 [ 3.16941794e+02 -8.53810255e+00  5.55111512e-16]
 [ 4.41468666e+02  2.32734957e+00  1.37667655e-14]
 [ 5.65995539e+02  1.31928017e+01  1.98729921e-14]]


Some sign inconsistencies are expected between the sklearn version and our implementation. This is fine as long as we train and reuse the model.