<div align="center">

<h1> MATHEMATICS CHEAT SHEET </h1>

</div>

**This jupyter notebook covers the all the basic mathematical priciples. I tried my best to cover the basics in a simple manner. More concepts would be added further.**

## LINEAR ALGEBRA

**Linear algebra is an important and vast field of mathematics. It encapsulates various sub-fields like;**

* Vector spaces
* Matrices
* Linear systems and Linear maps
* Duality

- For almost anything to do with linear algebra or particulary matrix operations we probably would use `numpy`. 


### Matrix

- Constructing a matrix

In [17]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C= np.array([[6, 5, 4], [3, 2, 1]])

print(f'A:\n {A}\n')
print(f'B:\n {B}\n')

print(type(A))

A:
 [[1 2 3]
 [4 5 6]]

B:
 [[1 2]
 [3 4]
 [5 6]]

<class 'numpy.ndarray'>


- Addition and Subtraction of matrices

In [20]:
print(f'Addition:\n {A+C}\n')
print(f'Subtraction:\n {A-C}')

Addition:
 [[7 7 7]
 [7 7 7]]

Subtraction:
 [[-5 -3 -1]
 [ 1  3  5]]


- Matrix multiplication

In [22]:
# dot product of two matrix

print(f'Multiplication:\n {A.dot(B)}')

Multiplication:
 [[22 28]
 [49 64]]


**We can perform matrix multiplication using the `dot()` function of numpy**

``` python

    a = np.array([[1, 2, 3], [4, 5, 6]])
    b = np.array([[1, 2], [3, 4], [5, 6]]) 
    
    c = a.dot(b)
```

>When multiplying two ndarray objects using the * operator, the result is the element-by-element multiplication. On the other hand, when multiplying two matrix objects using the * operator, the result is the dot (matrix) product which is equivalent to the np.dot()

### Matrix multiplication algorithm (Brute force approach)

``` python
    for each row i in C:
        for each col j in C:
            for k in 1 ... n:
                C[i][j] += A[i][k] * B[k][j]
```

### Time complexity of this algorithm is `O(` $N^{3}$ `)`

In [24]:
# matrix mult algo

def mat_mul(A, B):
    rows, cols, n = len(A), len(B[0]), len(B)
    
    C = [[0 for row in range(rows)] for col in range(cols)]
    
    # algo
    for i in range(rows):
        for j in range(cols):
            for k in range(n):
                
                C[i][j] += A[i][k] * B[k][j]
                
    return C


one = [[2, 3], [2, 1]]
two = [[3, 1], [1, 1]]

print(f'one * two:\n {mat_mul(one, two)}')
                
    

one * two:
 [[9, 5], [7, 3]]


- Transpose

In [26]:
print(f'Matrix A:\n {A}\n')

print(f'Transpose of A :\n {np.transpose(A)}')

Matrix A:
 [[1 2 3]
 [4 5 6]]

Transpose of A :
 [[1 4]
 [2 5]
 [3 6]]


- Trace (the sum of diagonal elements in a square matrix)

In [27]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'Original array: \n {m}\n')
print(f'Trace:  {m.trace()}')

Original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Trace:  15


- Rank 

In [28]:
from numpy import linalg as npl

print(f'Original Matrix: \n {m}\n')
print(f'Rank of the matrix is : {npl.matrix_rank(m)}')

Original Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank of the matrix is : 2


- Determinants

In [29]:
n = np.array([[1, 2, 3], [3, 2, 5], [6, 5, 7]])

print(f'Original Matrix: \n {n}\n')
print(f'Determinant of the matrix is : {npl.det(n):.0f}')

Original Matrix: 
 [[1 2 3]
 [3 2 5]
 [6 5 7]]

Determinant of the matrix is : 16


- Inverse (A square matrix would have inverse only if its determinant is non-zero)

In [33]:
print(f'Original Matrix: \n {n}\n')

print(f'Determinant of the matrix is : {npl.det(n):.0f}')

print(f'Inverse of the matrix is : \n {npl.inv(n)}')

Original Matrix: 
 [[1 2 3]
 [3 2 5]
 [6 5 7]]

Determinant of the matrix is : 16
Inverse of the matrix is : 
 [[-0.6875  0.0625  0.25  ]
 [ 0.5625 -0.6875  0.25  ]
 [ 0.1875  0.4375 -0.25  ]]


- Flatten (Flatten is a simple method to transform a matrix into a one-dimensional numpy array.)

In [37]:
print(f'Shape of original matrix: {n.shape}\n')
print(f'Original Matrix: \n {n}\n')

print(f'flattened matrix is : {n.flatten()}')


Shape of original matrix: (3, 3)

Original Matrix: 
 [[1 2 3]
 [3 2 5]
 [6 5 7]]

flattened matrix is : [1 2 3 3 2 5 6 5 7]


- Eigenvalues and Eigenvectors

In [50]:
print(f'Original Matrix: \n {n}\n')

w, v = npl.eig(n)

print(f'Eigenvalue :\n {w}\n\n')
print(f'Eigenvectors :\n {v}')
print(f'\nTrace of the vector: {n.trace()}')

Original Matrix: 
 [[1 2 3]
 [3 2 5]
 [6 5 7]]

Eigenvalue :
 [12.2324269 +0.j         -1.11621345+0.24913121j -1.11621345-0.24913121j]


Eigenvectors :
 [[-0.30530324+0.j         -0.01853889-0.3737954j  -0.01853889+0.3737954j ]
 [-0.4888339 +0.j          0.75984402+0.j          0.75984402-0.j        ]
 [-0.81720949+0.j         -0.4624439 +0.26213741j -0.4624439 -0.26213741j]]

Trace of the vector: 10


> Trace of the above vector is 10 which is equal to the sum of the eigenvalues (12 + (-1) + (-1))

## COMBINATORICS

**Combinatorics is a field of mathematics that deals mainly with counting, arranging, and analyzing the properties of discrete structures, such as sets, permutations, and graphs. Some important areas of study in combinatorics include;**

* Combinatorial optimization
* Graph theory
* Enumerative combinatorics

### There are several libraries in Python that can be used for combinatorics, including:

`itertools`: This built-in Python library provides a set of functions for working with iterators. It includes functions for generating permutations, combinations, and Cartesian products of input iterables.

`scipy.special`: This library, a part of the SciPy ecosystem, provides a set of special mathematical functions, including combinatorial functions like binomial coefficients, factorials, and permutations and combinations.

`networkx`: This library is used for the study of the structure, dynamics, and functions of complex networks. It provides classes for graph and digraph data structures, as well as functions for generating and manipulating such structures.

`SymPy`: This library is a Python library for symbolic mathematics, it includes combinatorial functions for permutations, combinations, and other discrete mathematics operations.

`combinations`: This library provides an implementation of the combinatorial iterators for python, it is a simple library that allows to iterate over the possible combinations of a given iterable in a very efficient way.


### While working with Combinatorial problems, it is important to keep in mind the time and space complexity of the algorithms used, combinatorial problems can grow exponentially

### Permutation and Combination

- We can use the `itertools` module of python to do permutation

In [9]:
from itertools import permutations, combinations

subjects = ('English', 'Python', 'Biology', 'Social Science', 'Mathematics')

arrangements = list(permutations(subjects, 3))

arrangements

[('English', 'Python', 'Biology'),
 ('English', 'Python', 'Social Science'),
 ('English', 'Python', 'Mathematics'),
 ('English', 'Biology', 'Python'),
 ('English', 'Biology', 'Social Science'),
 ('English', 'Biology', 'Mathematics'),
 ('English', 'Social Science', 'Python'),
 ('English', 'Social Science', 'Biology'),
 ('English', 'Social Science', 'Mathematics'),
 ('English', 'Mathematics', 'Python'),
 ('English', 'Mathematics', 'Biology'),
 ('English', 'Mathematics', 'Social Science'),
 ('Python', 'English', 'Biology'),
 ('Python', 'English', 'Social Science'),
 ('Python', 'English', 'Mathematics'),
 ('Python', 'Biology', 'English'),
 ('Python', 'Biology', 'Social Science'),
 ('Python', 'Biology', 'Mathematics'),
 ('Python', 'Social Science', 'English'),
 ('Python', 'Social Science', 'Biology'),
 ('Python', 'Social Science', 'Mathematics'),
 ('Python', 'Mathematics', 'English'),
 ('Python', 'Mathematics', 'Biology'),
 ('Python', 'Mathematics', 'Social Science'),
 ('Biology', 'English'

In [10]:
comb = list(combinations(subjects, 3))

comb

[('English', 'Python', 'Biology'),
 ('English', 'Python', 'Social Science'),
 ('English', 'Python', 'Mathematics'),
 ('English', 'Biology', 'Social Science'),
 ('English', 'Biology', 'Mathematics'),
 ('English', 'Social Science', 'Mathematics'),
 ('Python', 'Biology', 'Social Science'),
 ('Python', 'Biology', 'Mathematics'),
 ('Python', 'Social Science', 'Mathematics'),
 ('Biology', 'Social Science', 'Mathematics')]

- A practical example :

**How many 8 character passwords are possible using only the lowercase characters without repeating a character ?**

Since it is a password; the order matters hence we need to find the permuatation; of picking 8 letters from 26 letters and the permutation function would return the list of all the possible permutations, to find the final answer ie; no: of possible passwords; we just need to find the length of the list.

In [11]:
from string import ascii_lowercase as lowercase 

lowercase

'abcdefghijklmnopqrstuvwxyz'

In [12]:
pswd = permutations(lowercase, 8)

In [13]:
# Good luck running this

# print(len(list(pswd)))

### We can use scipy module to calculate factorials  

In [14]:
from scipy.special import factorial

n = 26
k = 8

print(factorial(n)/factorial(n-k))

62990928000.000015
