<h1 align="center" >  <font color="Orange"> Numpy ~ Exercises </font> </h1>

**Q1. Import numpy**

In [1]:
# Q1. Import numpy
import numpy as np

**Q2. print numpy version and configurations**

In [5]:
print('Version')
print(np.version)

print('\nConfig')
np.show_config()

Version
<module 'numpy.version' from 'c:\\Users\\kanna\\.conda\\envs\\ML\\Lib\\site-packages\\numpy\\version.py'>

Config
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kanna/.conda/envs/ML\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/kanna/.conda/envs/ML\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kanna/.conda/envs/ML\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/kanna/.conda/envs/ML\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kanna/.conda/envs/ML\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/kanna/.conda/envs/ML\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Us

**Q3. create a null vector of size 10**

In [6]:
arr = np.zeros(10, dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Q4. find the memory size of an array and np array containing same elements**

In [7]:
import sys

arr_normal = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr_np = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(f'Size of numpy array :{arr_np.itemsize*arr_np.size} bytes.')
print(f'Size of normal array :{sys.getsizeof(arr_normal)*len(arr_normal)} bytes.')

Size of numpy array :40 bytes.
Size of normal array :1360 bytes.


**Q5. How to get the documentation of the numpy add function from the command line?**

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**Q6. Create a null vector of size 10 but the fifth value which is 1**

In [9]:
arr_nullVec = np.zeros(10, dtype=int)
arr_nullVec[4] = 1
arr_nullVec

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

**Q7. Create a vector with values ranging from 10 to 49**

In [10]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**Q8. Reverse a vector (first element becomes last)**

In [11]:
arr_ToReverse = np.arange(1, 11)
arr_ToReverse[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

**Q9. Create a 3x3 matrix with values ranging from 0 to 8**

In [12]:
matrix1 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
matrix1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Q10. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [13]:
arr_ques = np.array([1,2,0,0,4,0])
print(np.nonzero(arr_ques))

(array([0, 1, 4], dtype=int64),)


**Q11. Create a 3x3 identity matrix**

In [14]:
arr_id = np.identity(3, dtype=int)
arr_id

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**Q12. Inbuilt numpy sorting**

In [15]:
names = np.array(['Mothra', 'Ghidorah', 'Shimomura'])

np.sort(names)

array(['Ghidorah', 'Mothra', 'Shimomura'], dtype='<U9')

**Q13. Element wise sorting**

In [16]:
arr1 = np.array(['a', 'b', 'h'])
arr2 = np.array(['c', 'f', 'd'])
arr1 > arr2

array([False, False,  True])

**Q14. How to double each element of an array.**

In [17]:
arr_to_double= np.array([[1,2, 3, 4],[7, 8, 9, 10],[2, 3, 4, 5],[5, 6, 7, 8]])

# Method 1
print("Double array-1: ", arr_to_double * 2)

# method 2
scale_arr = np.array([[2,2,2,2]])   # or this can also be { np.array([[2],[2],[2],[2]]) } or just 2

func = lambda x, y: x*y
vec_func = np.vectorize(func)
print("\nDouble array-2: \n",vec_func(arr_to_double, scale_arr))


Double array-1:  [[ 2  4  6  8]
 [14 16 18 20]
 [ 4  6  8 10]
 [10 12 14 16]]

Double array-2: 
 [[ 2  4  6  8]
 [14 16 18 20]
 [ 4  6  8 10]
 [10 12 14 16]]


**Q15. Find the output**

In [18]:
x = np.ones((5,5), dtype=int)
x[1:-1,1:-1] = 0
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**Q16. Add two randomly generated 3D Numpy matrices using loops**

In [16]:
arr1 = np.random.rand(4, 3, 2)
arr2 = np.random.rand(4, 3, 2)
ans = np.zeros((4, 3, 2))

for i in range(len(arr1)):
    for j in range(len(arr1[0])):
        for k in range(len(arr1[0][0])):
            ans[i][j][k] = arr1[i][j][k] + arr2[i][j][k]

print(ans)        

[[[0.96787572 1.30133504]
  [0.55480568 1.93224654]
  [0.73791215 1.40641976]]

 [[1.17790972 1.26108626]
  [1.0064385  0.580023  ]
  [0.82094862 1.54629813]]

 [[1.64192481 1.73003702]
  [0.59924845 0.0696746 ]
  [1.02757785 1.42935109]]

 [[0.30278753 0.76564295]
  [1.18599845 0.66552455]
  [1.65108752 0.64362642]]]
