<div align="center"> <h1> <font color="Orange"> Numpy - II </font> </h1> </div>

The real power of Numpy lies in its ability to perform **vectorized operations** { element-wise operations }. The vectorized operations are implemented through `ufuncs` { universal functions }.

`Aggregate/reduction Functions` are the functions in numpy that can be used to perform operations on the entire array. Some of the aggregate functions are:
- `np.sum()`
- `np.min()`
- `np.max()`
- `np.mean()`
- `np.any()`
- `np.all()`

In [1]:
import numpy as np

In [4]:
arr1 = np.arange(1, 13).reshape(3, 4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# sum()
print(np.sum(arr1))

# sum() along the 0-th dimension. Col wise
print(np.sum(arr1, axis=0))

# sum() along the 1-st dimension. row wise
print(np.sum(arr1, axis=1))

78
[15 18 21 24]
[10 26 42]


In [11]:
# mean()
print(np.mean(arr1), np.mean(arr1, axis=0, dtype=int), np.mean(arr1, axis=1), sep='\n')

6.5
[5 6 7 8]
[ 2.5  6.5 10.5]


In [13]:
# median
print(np.median(arr1), np.median(arr1, axis=0), np.median(arr1, axis=1), sep='\n')


6.5
[5. 6. 7. 8.]
[ 2.5  6.5 10.5]


In [15]:
# min
print(np.min(arr1), np.min(arr1, axis=0), np.min(arr1, axis=1), sep='\n')


1
[1 2 3 4]
[1 5 9]


In [26]:
# any()

print(np.array([1, 2, 3, 4]).any())
print(np.array([1, 0, 3, 0, 0]).any())
print(np.array([0, 0, 0, 0, 0]).any())

True
True
False


In [28]:
# nonzero() : return the indices of elements that are non-zero

print(np.array([1, 2, 3, 0]).nonzero())

(array([0, 1, 2], dtype=int64),)


In [32]:
print(np.array([1, 2, 5]) < np.array([1, 3, 2]))

[False  True False]


In [37]:
# using conditionals with any())
arr_first = np.array([5, 6, 3, 7, 9, 10])
arr_second = np.array([3, 1, 8, 7, 5, 5])

# check if there are any values in the first array such that it is smaller than the value at the same index in the second array.
print(np.any(arr_first < arr_second))

# any value at first array which is double of an element in the second index
print(np.any(arr_first == 2*arr_second))

True
True


In [38]:
# all() checks for all the elements
np.all(arr_first < arr_second)

False

In [39]:
np.all((arr_first <= arr_second) & (arr_second <= arr_first))

False

**`Sorting`**

In [14]:
arr_to_sort = np.random.randint(11, size=10)
print("Array to sort: ", arr_to_sort)

Array to sort:  [10  8  9 10  5  3  2  0  5  9]


In [28]:
np.sort(arr_to_sort)

array([ 0,  2,  3,  5,  5,  8,  9,  9, 10, 10])

- Quick sort (default) : 1.9 µs ± 64.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
- Merge sort : 1.97 µs ± 59.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
- heap sort : 1.92 µs ± 76.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
- Stable sort : 2.01 µs ± 29.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [31]:
arr2D_to_sort = np.random.randint(11, size=(3, 4))

In [42]:
# default sorting is in the last dim; for a matrix it sorts each row { matrix : col wise -> dim0, row wise -> dim1 }
print("Original array:\n", arr2D_to_sort)

Original array:
 [[ 2  4  6  6]
 [10  7 10  9]
 [ 4  2  4  7]]


In [45]:
print(np.sort(arr2D_to_sort, axis=0)) # col wise sort
np.sort(arr2D_to_sort)  # row wise sort

[[ 2  2  4  6]
 [ 4  4  6  7]
 [10  7 10  9]]


array([[ 2,  4,  6,  6],
       [ 7,  9, 10, 10],
       [ 2,  4,  4,  7]])

In [48]:
# argmax : Returns the indices of the maximum values along an axis.
arr23 = np.array([1, 3, 5, 7, 9])
print(np.max(arr23))

np.argmax(arr23)

9


4

In [50]:
# Matrix multiplication

mat1 = np.random.randint(11, size=(3, 4))
mat2 = np.random.randint(11, size=(4, 2))

print(mat1, mat2, sep='\n\n')
np.matmul(mat1, mat2)

[[ 0  6  1  8]
 [ 8 10  4  6]
 [ 6  3 10  8]]

[[ 6  0]
 [ 3  8]
 [ 8 10]
 [ 7  1]]


array([[ 82,  66],
       [152, 126],
       [181, 132]])

In [52]:
mat1 @ mat2 # we can perform matrix multiplication usign @ also.

array([[ 82,  66],
       [152, 126],
       [181, 132]])

In [53]:
# mat mul using dot() method
np.dot(mat1, mat2)

array([[ 82,  66],
       [152, 126],
       [181, 132]])