<div align="center"> <h1> <font color="Orange"> Numpy - I </font> </h1> </div>

`Numpy` or Numerical Python is a library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is basically used for performing numerical computations on arrays and matrices.

Numpy is implemented using `C` and `Python`, and the performance critical parts are written in C. Hence it is fast and efficient. It is also optimized for `vectorized operations` and thus it is extensively used for performing operations on individual elements.

The main object in Numpy is the `ndarray` or `n-dimensional array`. It is a `homogeneous multidimensional` array of fixed-size items. In Numpy dimensions are called `axes`. The number of axes is called `rank`. 

Some important numpy **functions/attributes** are:

- `ndarray.shape` - returns a tuple consisting of array dimensions (similar to (rows, columns))
- `ndarray.ndim` - returns the number of array dimensions
- `ndarray.size` - returns the total number of elements in the array
- `ndarray.dtype` - returns the type of elements in the array
- `ndarray.itemsize` - returns the size of each element in the array in bytes

- Like `range` in python numpy has `arange` which returns an array instead of a list. It also takes float arguments unlike `range`.

- Numpy also has something known as `linspace` which returns an array of evenly spaced numbers over a specified interval. It takes the number of elements as an argument instead of the step size. We use it when we want to divide a range into equal parts.

- We can use `reshape` to change the shape of an array. The number of elements in the array should be the same as the number of elements in the new shape. We also have `resize` which is similar to reshape but the number of elements in the array can be different from the number of elements in the new shape, if the number of elements is less than the number of elements in the new shape then the array will be filled by repeating the elements.
>**Note** : `np.resize()` and `arr.resize()` are different, `np.resize()` returns a new array with the new shape and `arr.resize()` changes the shape of the array in place, also `np.resize()` can take a tuple as the new shape and fills the remaining elements with *copies* while `arr.resize()` can only take a list as the new shape and fills the remaining elements with *zeros*.

- We can flatten an array (converting a multidimensional array into a 1D array) using `flatten` or `ravel`. `flatten` returns a copy of the array while `ravel` performs the operation in place.

Numpy also has a lot of functions for creating arrays like `zeros`, `ones`, `full`, `eye`, `random`, etc. Along with that it also has functions for performing operations on arrays like `min`, `max`, `sum`, `mean`, `std`, `var`, `argmin`, `argmax`, `cumsum`, `cumprod`, etc.

In [1]:
import numpy as np

In [2]:
# numpy arrays
np_arr = np.array([1, 2, 3, 4, 5, 6])

print(f'Array is {np_arr} \nType of array is: {type(np_arr)}')

# dimension
print("Dimension of array is: ", np_arr.ndim)

# shape (elements per dimension)
print("shape of the array: ", np_arr.shape)

# element wise operations
print("Squared list: ", np_arr**2)

# type casting
np_arr1 = np.array([1, 2, 3], dtype='float')
print("The new array is : ", np_arr1, "\nData type of the array is : ", np_arr1.dtype)


Array is [1 2 3 4 5 6] 
Type of array is: <class 'numpy.ndarray'>
Dimension of array is:  1
shape of the array:  (6,)
Squared list:  [ 1  4  9 16 25 36]
The new array is :  [1. 2. 3.] 
Data type of the array is :  float64


In [3]:
# arange()
print(np.arange(1, 5, 0.5))

# linspace
print(np.linspace(10, 100, 25))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [4]:
# Multi-dimensional arrays
np_2d_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 7, 6]])
print(f"Multi-dim array : \n{np_2d_arr}\nShape : {np_2d_arr.shape}\nDimension : {np_2d_arr.ndim}")

# Creating a matrix
m1 = np.arange(1, 13)
m1 = m1.reshape(3, 4)
# m2 = np.arange(12).reshape(3, 4)
print(f"\nMatrix is : \n{m1}\nShape of matrix: {m1.shape}\nDimension of matrix is: {m1.ndim}")

# np.resize()
m1 = np.resize(m1, (4, 4))
print(f"\nResized Matrix is (np.resize()) : \n{m1}\nShape of matrix: {m1.shape}\nDimension of matrix is: {m1.ndim}")

# arr.resize()
m3 = np.arange(4)
m3.resize((3, 4))
print(f"\nResized Matrix is (arr.resize()) : \n{m3}\nShape of matrix: {m3.shape}\nDimension of matrix is: {m3.ndim}")



Multi-dim array : 
[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]]
Shape : (3, 4)
Dimension : 2

Matrix is : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of matrix: (3, 4)
Dimension of matrix is: 2

Resized Matrix is (np.resize()) : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]
Shape of matrix: (4, 4)
Dimension of matrix is: 2

Resized Matrix is (arr.resize()) : 
[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
Shape of matrix: (3, 4)
Dimension of matrix is: 2


In [5]:
# flattening array
m4 = np.arange(16).reshape(4,-1) # when we put a negative value in the second index, numpy would automatically figure out the value

print(f"Original array is : \n{m4}\n\nFlattened array is : {m4.flatten()}")

Original array is : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Flattened array is : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [6]:
# array of zeros
zerro_arr = np.zeros(5, dtype='int') # by default it would give float values
zerro_arr1 = np.zeros((3, 4))

print("Array 1: ", zerro_arr, "\nArray 1: ", zerro_arr1)

# array of ones
one_arr = np.ones((2, 3), dtype='int') * 5
one_arr

Array 1:  [0 0 0 0 0] 
Array 1:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[5, 5, 5],
       [5, 5, 5]])

In [7]:
# diagonal matrix
diag_matrix = np.diag([1, 2, 3])
print("Diagonal Matrix : \n", diag_matrix)

# also we can get the list of diagonals from a diagonal matrix using the same diag() 
print("\nDiagonals are :", np.diag(diag_matrix))

# identity matrix
print("\nIdentity matrix : \n", np.identity(5, dtype=int))


Diagonal Matrix : 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

Diagonals are : [1 2 3]

Identity matrix : 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [8]:
# slicing / indexing
m5 = np.arange(1, 13).reshape(3, 4)
print(m5)

print(m5[2, 2]) # we can use normal slicing syntax but not appreciated

print(f"\nMultiple indexing : \n{m5[[1, 0, 1, 2, 2]]}")

# indexing multi dim array
print("\nMulti dim array indexing : \n", m5[[0, 1, 1], [2, 1, 0]]) # it would take one element of each sub list and index



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
11

Multiple indexing : 
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 9 10 11 12]]

Multi dim array indexing : 
 [3 6 5]


In [9]:
# masking / fancy indexing
print(m5, "\n")
print(m5 > 7, "\n")
print("All numbers > 7 :", m5[m5 > 7], "\n")
print("All multiple of 2 or multiples of 7 : ", m5[(m5 % 2 == 0) | (m5 % 7 == 0)])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[False False False False]
 [False False False  True]
 [ True  True  True  True]] 

All numbers > 7 : [ 8  9 10 11 12] 

All multiple of 2 or multiples of 7 :  [ 2  4  6  7  8 10 12]


In [13]:
# min, max, mean
print(f"Min value of the array :{m5.min()}\nmax value of the array :{m5.max()}\nMean value of the array :{m5.mean()}")

Min value of the array :1
max value of the array :12
Mean value of the array :6.5
