<div align="center"> <h1> <font color="Orange"> Numpy - I </font> </h1> </div>

#### $\text{1. Random arrays}$

There are many builtin ways to create random arrays in numpy.

#### $\text{2. View and Copy}$

For efficient memory management, NumPy uses views instead of copies whenever possible. This is a very important distinction between NumPy and Python sequences. In contrast, Python always creates new lists when objects are assigned to a new variable name, while numpy shares the same memory space for all variables that refer to the same array.

#### $\text{3. Broadcasting}$

Broadcasting is one of the key features of NumPy that makes it so powerful and easy to use. The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [1]:
import numpy as np

In [6]:
# Creating random arrays
a = np.random.rand(2, 3)    # random number in uniform distribution
a

array([[0.44424104, 0.09250562, 0.26395924],
       [0.09802076, 0.924068  , 0.9410409 ]])

In [8]:
b = np.random.randn(3, 4)   # random numbers in standard normal distribution or Gaussian distribution
b

array([[-0.7961423 , -0.44882091, -0.99257882,  0.36993366],
       [-1.19999297, -0.01864831,  0.27787967,  1.4546628 ],
       [-1.16466027,  0.86066504,  0.23395142,  0.33554757]])

In [13]:
c = np.arange(12).reshape(3, 4)
d = c[::2]

print(f'Array1 is \n{c}\nArray2 is \n{d}\n')
print(np.shares_memory(c,d))

Array1 is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array2 is 
[[ 0  1  2  3]
 [ 8  9 10 11]]

True


In [18]:
# Transcendental functions

e = np.arange(6)
print('Array: \n', e)

print('\nSin array: \n', np.sin(e))
print('\nLog Array: \n', np.log(e[1:]))
print('\nExponent Array: \n', np.exp(e))

Array: 
 [0 1 2 3 4 5]

Sin array: 
 [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

Log Array: 
 [0.         0.69314718 1.09861229 1.38629436 1.60943791]

Exponent Array: 
 [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
