<h1 align="center" >  <font color="Orange"> Numpy ~ Exercises </font> </h1>

1. Print numpy version and configurations

2. Create a null vector of size 10 (an array of 10 zeros)

3. Find the memory size of an array and np array containing same elements

4. Reverse a vector (first element becomes last)

5. Create a 3x3 matrix with values ranging from 0 to 8

6. Find indices of non-zero elements from [1,2,0,0,4,0]

7. Sort an array

8. Double each element of an array

9. Add two randomly generated 3D tensors using loops

10. Create a function which displays a summary report (mean, median, variance, standard deviation) of the given numpy array

11. Replace all odd numbers in an array with -1, without changing the array

In [1]:
import numpy as np

In [ ]:
# Print numpy version and configurations
print('Version :', np.__version__)

print('\nConfig')
np.show_config()

In [ ]:
# Create a null vector of size 10 (an array of 10 zeros)
arr = np.zeros(10, dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Find the memory size of an array and np array containing same elements
import sys


arr_normal = [x for x in range(1, 1001)]
arr_np = np.array(np.arange(1, 1001))

np_array_size = arr_np.itemsize * arr_np.size

list_size = sys.getsizeof(arr_normal) + sum(sys.getsizeof(x) for x in arr_normal)

print(f'Size of numpy array: {np_array_size/1000} Kilobytes')
print(f'Size of normal array: {list_size/1000:.3f} kilobytes.')


Size of numpy array: 8.0 Kilobytes
Size of normal array: 36.856 kilobytes.


In [21]:
# Reverse a vector (first element becomes last)
vector_to_reverse = np.arange(1, 11)
print(vector_to_reverse)
vector_to_reverse = vector_to_reverse[::-1]
print(vector_to_reverse)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [24]:
# Create a 3x3 matrix with values ranging from 0 to 8
matrix1 = np.arange(9).reshape((3, 3))
matrix1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr_non_zero = np.array([1,2,0,0,4,0])
print(*np.nonzero(arr_non_zero)[0])

0 1 4


In [10]:
names = np.array(['Mothra', 'Ghidorah', 'Shimomura'])

sorted_names = np.sort(names)
sorted_names

array(['Ghidorah', 'Mothra', 'Shimomura'], dtype='<U9')

In [19]:
# double each element of an array
arr_to_double= np.array([[1,2, 3, 4],[7, 8, 9, 10],[2, 3, 4, 5],[5, 6, 7, 8]])

print(f"Original Array : \n{arr_to_double}\n")
print(f"Doubled Array : \n{arr_to_double * 2}")


Original Array : 
[[ 1  2  3  4]
 [ 7  8  9 10]
 [ 2  3  4  5]
 [ 5  6  7  8]]

Doubled Array : 
[[ 2  4  6  8]
 [14 16 18 20]
 [ 4  6  8 10]
 [10 12 14 16]]


In [26]:
# Add two randomly generated 3D tensors using loops
random_array_1 = np.random.randint(1, 100, 24).reshape((4, 3, 2))
random_array_2 = np.random.randint(1, 100, 24).reshape((4, 3, 2))
ans = np.zeros((4, 3, 2))

print(f"Input Tensor 1 :\n{random_array_1}\n")
print(f"Input Tensor 2 :\n{random_array_2}\n")

for i in range(len(random_array_1)):
    for j in range(len(random_array_1[0])):
        for k in range(len(random_array_1[0][0])):
            ans[i][j][k] = random_array_1[i][j][k] + random_array_2[i][j][k]

print(f"Input Tensor 1 + Input Tensor 2 : \n{ans}")
# ans2 = random_array_1 + random_array_2 # using broadcasting -> much efficient   
# print(f"Input Tensor 1 + Input Tensor 2 : \n{ans2}")

Input Tensor 1 :
[[[21 50]
  [25  5]
  [94 36]]

 [[72 54]
  [44 17]
  [36  7]]

 [[34  4]
  [12 84]
  [63 63]]

 [[23  3]
  [80 77]
  [86 58]]]

Input Tensor 2 :
[[[46 88]
  [24 57]
  [77 94]]

 [[ 1  3]
  [57 34]
  [25 86]]

 [[35 84]
  [37 42]
  [23 79]]

 [[80  8]
  [62 70]
  [24 63]]]

Input Tensor 1 + Input Tensor 2 : 
[[[ 67. 138.]
  [ 49.  62.]
  [171. 130.]]

 [[ 73.  57.]
  [101.  51.]
  [ 61.  93.]]

 [[ 69.  88.]
  [ 49. 126.]
  [ 86. 142.]]

 [[103.  11.]
  [142. 147.]
  [110. 121.]]]


In [31]:
# Create a function which displays a summary report (mean, median, variance, standard deviation) of the given numpy array
def summary_report(data: np.ndarray):
    print(f'Mean : {np.mean(data):.3f}')

    print(f'Median : {np.median(data):.3f}')

    print(f'Variance : {np.var(data):.3f}')

    print(f'Variance : {np.std(data):.3f}')


data = 0.6 * (np.random.randint(1, 100, 100)) + 27
summary_report(data)

Mean : 54.786
Median : 55.200
Variance : 287.544
Variance : 16.957


In [34]:
# Replace all odd numbers in an array with -1, without changing the array
array_1 = np.array([1, 2, 3, 4, 5, 6, 7, 6, 4, 3, 2, 1])
array_out = np.where(array_1 % 2 == 1, -1, array_1)
print(f"Original Array :\n{array_1}")
print(f"Changed Array :\n{array_out}")

Original Array :
[1 2 3 4 5 6 7 6 4 3 2 1]
Changed Array :
[-1  2 -1  4 -1  6 -1  6  4 -1  2 -1]


In [ ]:
# element wise comparison
array_2 = np.array(['a', 'b', 'h'])
array_3 = np.array(['c', 'f', 'd'])
array_2 > array_3

array([False, False,  True])