<div align="center"> <h1> <font color="Orange"> Numpy - I </font> </h1> </div>

In [1]:
import numpy as np

### Basic Operations

In [3]:
# numpy arrays
np_arr = np.array([1, 2, 3, 4, 5, 6])

print(f'Array is {np_arr} \nType of array is: {type(np_arr)}')

# dimension
print("Dimension of array is: ", np_arr.ndim)

# shape (elements per dimension)
print("shape of the array: ", np_arr.shape)

# Size
print("Size : ", np_arr.size)

# Data type
print("Data type : ", np_arr.dtype)

# Item size
print("Item size : ", np_arr.itemsize)

# element wise operations
print("Squared list: ", np_arr**2)

# type casting
np_arr1 = np.array([1, 2, 3], dtype='float')
print("The new array is : ", np_arr1, "\nData type of the array is : ", np_arr1.dtype)

# buffer containing actual data
print("Memory : ", np_arr.data)

Array is [1 2 3 4 5 6] 
Type of array is: <class 'numpy.ndarray'>
Dimension of array is:  1
shape of the array:  (6,)
Size :  6
Data type :  int32
Item size :  4
Squared list:  [ 1  4  9 16 25 36]
The new array is :  [1. 2. 3.] 
Data type of the array is :  float64
Memory :  <memory at 0x0000025C5A2D90C0>


### Creating arrays

In [4]:
# arange()
print("arange : ", np.arange(1, 5, 0.5))
print('---------------------------------------------------\n')

# linspace
print("linspace : ", np.linspace(10, 100, 25))
print('--------------------------------------------------\n')

# empty
print("empty : ", np.empty([2, 3])) # random values at first
print('--------------------------------------------------\n')

# zeros
print("zeros : ", np.zeros([2, 3, 2]))
print('--------------------------------------------------\n')

# ones
print("ones : ", np.ones([2, 3, 2]))
print('--------------------------------------------------\n')

# full()
print("full(8) : ", np.full([2, 3], 8, dtype=int))
print('--------------------------------------------------\n')

arange :  [1.  1.5 2.  2.5 3.  3.5 4.  4.5]
---------------------------------------------------

linspace :  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
--------------------------------------------------

empty :  [[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.33511018e-306 1.89146896e-307 7.56571288e-307]]
--------------------------------------------------

zeros :  [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
--------------------------------------------------

ones :  [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
--------------------------------------------------

full(8) :  [[8 8 8]
 [8 8 8]]
--------------------------------------------------



### Stacking or Combining arrays

In [5]:
# v-stack
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([5, 4, 3, 2, 1])
a3 = np.vstack((a1, a2))
print("a3 : ", a3, "\nShape : ", a3.shape)

# h-stack
a4 = np.array([[1, 2], [3, 4]])
a5 = np.hstack((a3, a4))
print("\n\na5 : ", a5, "\nShape : ", a5.shape)

# d-stack
a6 = np.array([[10, 9, 8, 7, 6], [11, 12, 13, 14, 15]])
a7 = np.dstack((a3, a6))
print("\n\na7 : ", a7, "\nShape : ", a7.shape)

# concatenate
a8 = np.concatenate((a3, a4), axis=1)
print("\na8 : ", a8, "\nShape : ", a8.shape)

a3 :  [[1 2 3 4 5]
 [5 4 3 2 1]] 
Shape :  (2, 5)


a5 :  [[1 2 3 4 5 1 2]
 [5 4 3 2 1 3 4]] 
Shape :  (2, 7)


a7 :  [[[ 1 10]
  [ 2  9]
  [ 3  8]
  [ 4  7]
  [ 5  6]]

 [[ 5 11]
  [ 4 12]
  [ 3 13]
  [ 2 14]
  [ 1 15]]] 
Shape :  (2, 5, 2)

a8 :  [[1 2 3 4 5 1 2]
 [5 4 3 2 1 3 4]] 
Shape :  (2, 7)


### Indexing - Slicing - Reshaping

In [23]:
a10 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Indexing
print(f'Row 1 : {a10[0]}')
print(f'\nFirst element : {a10[0, 0]}')
print(f'\nMultiple indexing : \n{a10[[2, 1, 1, 0]]}')
print(f'\nMulti dimensional indexing : \n{a10[[0, 1, 2, 1], [1, 2, 1, 0]]}')
print(f'\nAll numbers greater than 4 : {a10[a10 > 4]}')
print(f'\nMask for all numbers less than 3 : {a10 < 3}')
print(f'\nNumbers which are multiple of 2 and 3 : {a10[(a10 % 2 == 0) & (a10 % 3 == 0)]}')
print(f'\nNumbers which are multiple of 2 or 3 : {a10[(a10 % 2 == 0) | (a10 % 3 == 0)]}')
print('---------------------------------------------------------------------')

# Slicing
print(f'Col 1 : ', a10[:, 0])

split = 2
train, test = a10[:split, :], a10[split:, :]
print('\nTrain : ', train)
print('Test : ', test)

Row 1 : [1 2 3]

First element : 1

Multiple indexing : 
[[7 8 9]
 [4 5 6]
 [4 5 6]
 [1 2 3]]

Multi dimensional indexing : 
[2 6 8 4]

All numbers greater than 4 : [5 6 7 8 9]

Mask for all numbers less than 3 : [[ True  True False]
 [False False False]
 [False False False]]

Numbers which are multiple of 2 and 3 : [6]

Numbers which are multiple of 2 or 3 : [2 3 4 6 8 9]
---------------------------------------------------------------------
Col 1 :  [1 4 7]

Train :  [[1 2 3]
 [4 5 6]]
Test :  [[7 8 9]]


In [17]:
# Reshape
a11 = np.arange(1, 21)
print("\nOriginal array : ", a11)

# -1  means auto inference
a11 = a11.reshape((5, -1))
print("\nUsing -1 to auto infer col num : ", a11)

# int mean 1D array
a11 = a11.reshape(20)
print("\nSingle dimensional array : ", a11)

# 'C' row major order or c type implementation
a11 = np.reshape(a11, (2, 10), 'C')
print("\nRow major order of C-based order : ", a11)

# 'F' Fortran or col major order
a11 = np.reshape(a11, (5, -1), 'F')
print("\nCol major order of Fortran-based order : ", a11)
print('---------------------------------------------------------------------')

# 1D array to 2D array (one col multiple arrays)
a12 = np.arange(1, 11, dtype=int)
a12 = a12.reshape((a12.shape[0], 1))
print(f'\nReshaped array : \n{a12}')

# 2D array to 3D array (multiple matrices)
a10 = a10.reshape(a10.shape[0], a10.shape[1], 1)
print(f'3D array : \n{a10}\nShape of 3D array is {a10.shape}')
print('---------------------------------------------------------------------')

a13 = np.arange(1, 13)
print('\nOriginal array : ', a13)

# np.resize()
a13 = np.resize(a13, (4, 3))
print('Resized array (np.resize()) : ', a13)

# ndarray.resize()
a14 = np.arange(1, 5)
print('\nOriginal array : ', a14)

a14.resize(2, 4)
print('Resized array (ndarray.resize()) : ', a14)
print('---------------------------------------------------------------------')

# flattening array
print("Flattening array : ", a13.flatten())


Original array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Using -1 to auto infer col num :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

Single dimensional array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Row major order of C-based order :  [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

Col major order of Fortran-based order :  [[ 1 13  6 18]
 [11  4 16  9]
 [ 2 14  7 19]
 [12  5 17 10]
 [ 3 15  8 20]]
---------------------------------------------------------------------

Reshaped array : 
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
3D array : 
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
Shape of 3D array is (3, 3, 1)
---------------------------------------------------------------------

Original array :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Resized array (np.resize()) :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Original array :  [1 2 3 4]
Resiz