<div align="center"> <h1> <font color="Orange"> Numpy - I </font> </h1> </div>

In [1]:
import numpy as np

### Basic Operations

In [34]:
# numpy arrays
np_arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# numpy array
print(f"Array :\n{np_arr}")
print('--------------------------------------------------\n')

# type of object
print(f"Type of array is : {type(np_arr)}")
print('--------------------------------------------------\n')

# shape (elements per dimension)
print("shape of the array : ", np_arr.shape)
print('--------------------------------------------------\n')

# dimension
print("Dimension of array is (ndim) : ", np_arr.ndim)
print('--------------------------------------------------\n')

# Size
print("Size : ", np_arr.size)
print('--------------------------------------------------\n')

# Data type
print("Data type : ", np_arr.dtype)
print('--------------------------------------------------\n')

# Item size
print(f"Item size : {np_arr.itemsize} bytes")
print('--------------------------------------------------\n')

# Total size
print(f"Total bytes: {np_arr.nbytes}")
print('--------------------------------------------------\n')

# bytes to next row/col
print(f"Strides: {np_arr.strides}")
print('--------------------------------------------------\n')

# buffer containing actual data
print("Memory : ", np_arr.data)
print('--------------------------------------------------\n')

# element wise operations
print("Element wise operation (Squared list):\n", np_arr**2)

Array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------------------------------

Type of array is : <class 'numpy.ndarray'>
--------------------------------------------------

shape of the array :  (3, 4)
--------------------------------------------------

Dimension of array is (ndim) :  2
--------------------------------------------------

Size :  12
--------------------------------------------------

Data type :  int64
--------------------------------------------------

Item size : 8 bytes
--------------------------------------------------

Total bytes: 96
--------------------------------------------------

Strides: (32, 8)
--------------------------------------------------

Memory :  <memory at 0x0000022D44C92810>
--------------------------------------------------

Element wise operation (Squared list):
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


### Understanding axes with examples

In [3]:
arr_1d = np.array([1, 2, 3, 4])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"1D array - axes: {arr_1d.ndim}, shape: {arr_1d.shape}")
print(f"2D array - axes: {arr_2d.ndim}, shape: {arr_2d.shape}")
print(f"3D array - axes: {arr_3d.ndim}, shape: {arr_3d.shape}")

1D array - axes: 1, shape: (4,)
2D array - axes: 2, shape: (2, 3)
3D array - axes: 3, shape: (2, 2, 2)


### Memory layout explanation using `strides`

In [4]:
# Understanding strides
arr = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=np.int32)

print(f"Shape: {arr.shape}")
print(f"Strides: {arr.strides}")
print(f"Item size: {arr.itemsize} bytes")

# Strides explanation:
# - To move to next row: skip 12 bytes (3 elements × 4 bytes)
# - To move to next column: skip 4 bytes (1 element × 4 bytes)

Shape: (2, 3)
Strides: (12, 4)
Item size: 4 bytes


### Array Creation

In [24]:
# 1D array from list
arr1 = np.array([1, 2, 3, 4, 5])
print(f"1D array: {arr1}")
print('--------------------------------------------------\n')

# 2D array from nested lists
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D array:\n{arr2}")
print('--------------------------------------------------\n')

# Explicitly specify data type
arr3 = np.array([1, 2, 3], dtype=np.float64)
print(f"Float array: {arr3}, dtype: {arr3.dtype}")
print('--------------------------------------------------\n')

# From tuple
arr4 = np.array((1, 2, 3, 4))
print(f"From tuple: {arr4}")

1D array: [1 2 3 4 5]
--------------------------------------------------

2D array:
[[1 2 3]
 [4 5 6]]
--------------------------------------------------

Float array: [1. 2. 3.], dtype: float64
--------------------------------------------------

From tuple: [1 2 3 4]


#### Array Generation Functions

- `arange`
- `linspace`
- `logspace`

In [18]:
# Basic usage
arr1 = np.arange(10)                    # 0 to 9
arr2 = np.arange(5, 15)                 # 5 to 14
arr3 = np.arange(0, 10, 2)              # 0, 2, 4, 6, 8 (start, end, step)
arr4 = np.arange(0, 1, 0.1)             # Supports floats (unlike range); but prefer linspace while dealing with floats

print(f"arange(10): {arr1}")
print('--------------------------------------------------\n')
print(f"arange(5, 15): {arr2}")
print('--------------------------------------------------\n')
print(f"arange(0, 10, 2): {arr3}")
print('--------------------------------------------------\n')
print(f"arange(0, 1, 0.1): {arr4}")
print('--------------------------------------------------\n')

# data type argument
arr5 = np.arange(1, 101, dtype='int8')
arr6 = np.arange(1, 101)

print(f"Total bytes of arr5 (int8) :{arr5.nbytes}")
print(f"Total bytes of arr6 (int64) :{arr6.nbytes}")

arange(10): [0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------

arange(5, 15): [ 5  6  7  8  9 10 11 12 13 14]
--------------------------------------------------

arange(0, 10, 2): [0 2 4 6 8]
--------------------------------------------------

arange(0, 1, 0.1): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
--------------------------------------------------

Total bytes of arr5 (int8) :100
Total bytes of arr6 (int64) :800


In [27]:
# Creates evenly spaced numbers over specified interval
arr1 = np.linspace(0, 10, 5)            # 5 points from 0 to 10
arr2 = np.linspace(0, 1, 11)            # 11 points from 0 to 1
arr3 = np.linspace(0, 10, 5, endpoint=False)  # Exclude endpoint

print(f"linspace(0, 10, 5): {arr1}")
print('--------------------------------------------------\n')
print(f"linspace(0, 1, 11): {arr2}")
print('--------------------------------------------------\n')
print(f"linspace(0, 10, 5, endpoint=False): {arr3}")
print('--------------------------------------------------\n')

# Get the step size
arr, step = np.linspace(0, 10, 5, retstep=True)
print(f"Array: {arr}, Step: {step}")

linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]
--------------------------------------------------

linspace(0, 1, 11): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
--------------------------------------------------

linspace(0, 10, 5, endpoint=False): [0. 2. 4. 6. 8.]
--------------------------------------------------

Array: [ 0.   2.5  5.   7.5 10. ], Step: 2.5


In [28]:
# Creates numbers spaced evenly on a log scale
arr1 = np.logspace(0, 3, 4)             # 10^0 to 10^3, 4 points
arr2 = np.logspace(1, 3, 3, base=2)     # 2^1 to 2^3, 3 points

print(f"logspace(0, 3, 4): {arr1}")
print('--------------------------------------------------\n')
print(f"logspace(1, 3, 3, base=2): {arr2}")

logspace(0, 3, 4): [   1.   10.  100. 1000.]
--------------------------------------------------

logspace(1, 3, 3, base=2): [2. 4. 8.]


### Initialization / Placeholder Arrays

- Zeros, Ones, empty, and Full Arrays
- Identity and Eye matrices

In [15]:
# Create arrays filled with specific values
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((3, 4))
zeros_int = np.zeros((2, 3), dtype=np.int32)

ones_1d = np.ones(5)
ones_2d = np.ones((2, 3))

uninitialized_arr = np.empty((2, 3))

full_arr = np.full((3, 3), 7)           # Fill with 7
full_pi = np.full((2, 4), np.pi)        # Fill with π

print(f"Zeros 1D: {zeros_1d}")
print(f"\nZeros 2D:\n{zeros_2d}")
print(f"\nOnes 2D:\n{ones_2d}")
print(f"\nUninitialized array (Garbage values) :\n{uninitialized_arr}")
print(f"\nFull (7):\n{full_arr}")
print(f"\nFull (π):\n{full_pi}")

Zeros 1D: [0. 0. 0. 0. 0.]

Zeros 2D:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones 2D:
[[1. 1. 1.]
 [1. 1. 1.]]

Uninitialized array (Garbage values) :
[[1. 1. 1.]
 [1. 1. 1.]]

Full (7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Full (π):
[[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]


In [29]:
# Identity matrix (diagonal of ones)
identity = np.eye(4)
print(f"Identity 4x4:\n{identity}")
print('--------------------------------------------------\n')

# Identity with different dimensions
identity_rect = np.eye(3, 5)
print(f"Identity 3x5:\n{identity_rect}")
print('--------------------------------------------------\n')

# Diagonal offset
eye_offset = np.eye(4, k=1)  # Diagonal shifted up by 1
print(f"Eye with k=1:\n{eye_offset}")
print('--------------------------------------------------\n')

# Create diagonal matrix from array
diag_arr = np.diag([1, 2, 3, 4])
print(f"Diagonal from array:\n{diag_arr}")

Identity 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------------------------------------

Identity 3x5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
--------------------------------------------------

Eye with k=1:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
--------------------------------------------------

Diagonal from array:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### Arrays from Existing Arrays

In [30]:
# Create arrays with same shape as existing arrays
original = np.array([[1, 2, 3], [4, 5, 6]])

zeros_like = np.zeros_like(original)
ones_like = np.ones_like(original)
empty_like = np.empty_like(original)
full_like = np.full_like(original, 9)

print(f"Original:\n{original}")
print('--------------------------------------------------\n')
print(f"Zeros like:\n{zeros_like}")
print('--------------------------------------------------\n')
print(f"Ones like:\n{ones_like}")
print('--------------------------------------------------\n')
print(f"Full like (9):\n{full_like}")

Original:
[[1 2 3]
 [4 5 6]]
--------------------------------------------------

Zeros like:
[[0 0 0]
 [0 0 0]]
--------------------------------------------------

Ones like:
[[1 1 1]
 [1 1 1]]
--------------------------------------------------

Full like (9):
[[9 9 9]
 [9 9 9]]


### From Functions (`fromfunction`)

In [31]:
# Create array by executing a function over each coordinate
def func(i, j):
    return i + j

arr = np.fromfunction(func, (4, 5), dtype=int)
print(f"Array from function:\n{arr}")
print('--------------------------------------------------\n')

# Create multiplication table
def mult_table(i, j):
    return (i + 1) * (j + 1)

table = np.fromfunction(mult_table, (5, 5), dtype=int)
print(f"Multiplication table:\n{table}")

Array from function:
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
--------------------------------------------------

Multiplication table:
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


### Data types

In [20]:
# Exploring data types
int8_arr = np.array([1, 2, 3], dtype=np.int8)
float16_arr = np.array([1.5, 2.5], dtype=np.float16)
bool_arr = np.array([True, False, True], dtype=np.bool_)

print(f"int8: {int8_arr}, size: {int8_arr.itemsize} bytes")
print(f"float16: {float16_arr}, size: {float16_arr.itemsize} bytes")
print(f"bool: {bool_arr}, size: {bool_arr.itemsize} bytes")

# Type info
print(f"\nint8 info: {np.iinfo(np.int8)}")
print(f"float64 info: {np.finfo(np.float64)}")

int8: [1 2 3], size: 1 bytes
float16: [1.5 2.5], size: 2 bytes
bool: [ True False  True], size: 1 bytes

int8 info: Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

float64 info: Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------



### Type conversion

In [21]:
# Automatic type promotion
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.array([1.5, 2.5, 3.5], dtype=np.float64)
result = arr1 + arr2  # int32 promoted to float64
print(f"int32 + float64 = {result.dtype}: {result}")

# Explicit type casting
float_arr = np.array([1.7, 2.8, 3.9])
int_arr = float_arr.astype(np.int32)  # Truncates decimals
print(f"Float to int: {int_arr}")

# Safe casting check
can_cast = np.can_cast(np.float64, np.int32)
print(f"Can safely cast float64 to int32? {can_cast}")

int32 + float64 = float64: [2.5 4.5 6.5]
Float to int: [1 2 3]
Can safely cast float64 to int32? False


### Memory Considerations 

In [22]:
# Memory comparison
n = 1_000_000

arr_int64 = np.ones(n, dtype=np.int64)
arr_int32 = np.ones(n, dtype=np.int32)
arr_int8 = np.ones(n, dtype=np.int8)

print(f"int64: {arr_int64.nbytes / 1e6:.2f} MB")
print(f"int32: {arr_int32.nbytes / 1e6:.2f} MB (50% reduction)")
print(f"int8:  {arr_int8.nbytes / 1e6:.2f} MB (87.5% reduction)")

# For datasets with categorical data (e.g., age 0-120)
ages = np.random.randint(0, 120, size=1_000_000, dtype=np.uint8)
print(f"\nAges array: {ages.nbytes / 1e6:.2f} MB")

int64: 8.00 MB
int32: 4.00 MB (50% reduction)
int8:  1.00 MB (87.5% reduction)

Ages array: 1.00 MB


### Stacking Arrays

In [35]:
# v-stack
# Stacking arrays vertically (row-wise)
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])
arr3 = np.array([[7, 8, 9]])

vstacked = np.vstack((arr1, arr2, arr3))
print(f"Vertically stacked:\n{vstacked}")
print(f"Shape: {vstacked.shape}")
print('--------------------------------------------------\n')

# h-stack
# Stacking arrays horizontally (column-wise)
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4], [5], [6]])
arr3 = np.array([[7], [8], [9]])

hstacked = np.hstack((arr1, arr2, arr3))
print(f"Horizontally stacked:\n{hstacked}")
print(f"Shape: {hstacked.shape}")
print('--------------------------------------------------\n')

# d-stack
# Stacking arrays depth-wise (along 3rd axis)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

dstacked = np.dstack((arr1, arr2))
print(f"Depth stacked:\n{dstacked}")
print(f"Shape: {dstacked.shape}")

Vertically stacked:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
--------------------------------------------------

Horizontally stacked:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Shape: (3, 3)
--------------------------------------------------

Depth stacked:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape: (2, 2, 2)


### concatenate

In [3]:
# Concatenate along specified axis
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# axis=0 (vertical)
concat_0 = np.concatenate((arr1, arr2), axis=0)
print(f"Concatenate axis=0:\n{concat_0}")
print('--------------------------------------------------\n')

# axis=1 (horizontal)
concat_1 = np.concatenate((arr1, arr2), axis=1)
print(f"Concatenate axis=1:\n{concat_1}")
print('--------------------------------------------------\n')

# 1D concatenation
arr_1d_1 = np.array([1, 2, 3])
arr_1d_2 = np.array([4, 5, 6])
concat_1d = np.concatenate((arr_1d_1, arr_1d_2))
print(f"1D concatenate: {concat_1d}")

Concatenate axis=0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------------------------------------

Concatenate axis=1:
[[1 2 5 6]
 [3 4 7 8]]
--------------------------------------------------

1D concatenate: [1 2 3 4 5 6]


### Splitting Arrays

In [4]:
# Split array into equal parts
arr = np.arange(12).reshape(3, 4)
print(f"Original:\n{arr}\n")
print('--------------------------------------------------\n')

# Horizontal split (split columns)
h1, h2 = np.hsplit(arr, 2)
print(f"Horizontal split 1:\n{h1}")
print(f"\nHorizontal split 2:\n{h2}\n")
print('--------------------------------------------------\n')

# Vertical split (split rows)
v1, v2, v3 = np.vsplit(arr, 3)
print(f"Vertical split 1:\n{v1}")
print(f"\nVertical split 2:\n{v2}")
print(f"\nVertical split 3:\n{v3}")

Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

--------------------------------------------------

Horizontal split 1:
[[0 1]
 [4 5]
 [8 9]]

Horizontal split 2:
[[ 2  3]
 [ 6  7]
 [10 11]]

--------------------------------------------------

Vertical split 1:
[[0 1 2 3]]

Vertical split 2:
[[4 5 6 7]]

Vertical split 3:
[[ 8  9 10 11]]


### Repeating and Tiling    

In [5]:
# Repeat elements
arr = np.array([1, 2, 3])
repeated = np.repeat(arr, 3)
print(f"Repeated: {repeated}")
print('--------------------------------------------------\n')

# Repeat with different counts per element
repeated_var = np.repeat(arr, [2, 3, 1])
print(f"Repeated (variable): {repeated_var}")
print('--------------------------------------------------\n')

# Tile array
arr_2d = np.array([[1, 2], [3, 4]])
tiled = np.tile(arr_2d, (2, 3))  # Repeat 2 times vertically, 3 times horizontally
print(f"Tiled:\n{tiled}")

Repeated: [1 1 1 2 2 2 3 3 3]
--------------------------------------------------

Repeated (variable): [1 1 2 2 2 3]
--------------------------------------------------

Tiled:
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


### Indexing - Slicing - Reshaping

In [7]:
# 1D indexing
arr = np.array([10, 20, 30, 40, 50])
print(f"arr[0]: {arr[0]}")      # First element
print(f"\narr[-1]: {arr[-1]}")    # Last element
print(f"\narr[2]: {arr[2]}")      # Third element

# 2D indexing
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print(f"\narr_2d[0, 3]: {arr_2d[0, 3]}")     # Row 0, column 3
print(f"\narr_2d[1, 2]: {arr_2d[1, 2]}")       # Row 1, column 2
print(f"\narr_2d[-1, -1]: {arr_2d[-1, -1]}")   # Last element

# Accessing entire rows/columns
print(f"Row 1: {arr_2d[1]}")                  # Entire row 1
print(f"Column 2: {arr_2d[:, 2]}")            # Entire column 2

arr[0]: 10

arr[-1]: 50

arr[2]: 30

arr_2d[0, 3]: 4

arr_2d[1, 2]: 7

arr_2d[-1, -1]: 12
Row 1: [5 6 7 8]
Column 2: [ 3  7 11]


In [ ]:
# Select specific elements using integer arrays
arr = np.array([10, 20, 30, 40, 50, 60])
indices = np.array([0, 2, 4])
selected = arr[indices]
print(f"Selected elements: {selected}")
print('--------------------------------------------------\n')

# 2D integer array indexing
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select specific rows
rows = np.array([0, 2])
selected_rows = arr_2d[rows]
print(f"Selected rows:\n{selected_rows}")
print('--------------------------------------------------\n')

# Select specific elements (row, col pairs)
rows = np.array([0, 1, 2])
cols = np.array([0, 1, 2])
diagonal = arr_2d[rows, cols]
print(f"Diagonal elements: {diagonal}")

# Other types
print(f'\nAll numbers greater than 4 : {arr_2d[arr_2d > 4]}')

Selected elements: [10 30 50]
--------------------------------------------------

Selected rows:
[[1 2 3]
 [7 8 9]]
--------------------------------------------------

Diagonal elements: [1 5 9]


In [13]:
# 1D slicing
arr = np.arange(10)
print(f"arr[2:7]: {arr[2:7]}")        # Elements from index 2 to 6
print(f"arr[:5]: {arr[:5]}")          # First 5 elements
print(f"arr[5:]: {arr[5:]}")          # From index 5 to end
print(f"arr[::2]: {arr[::2]}")        # Every 2nd element
print(f"arr[::-1]: {arr[::-1]}")      # Reverse array

# 2D slicing
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print(f"\nFirst 2 rows:\n{arr_2d[:2]}")
print('--------------------------------------------------\n')
print(f"Last 2 columns:\n{arr_2d[:, -2:]}")
print('--------------------------------------------------\n')
print(f"Center 2x2 block:\n{arr_2d[1:3, 1:3]}")
print('--------------------------------------------------\n')
print(f"Every other element:\n{arr_2d[::2, ::2]}")
print('--------------------------------------------------\n')

# Slicing example for train-test split
split = 2
train, test = arr_2d[:split, :], arr_2d[split:, :]
print('Train :\n', train)

print('\nTest :\n', test)

arr[2:7]: [2 3 4 5 6]
arr[:5]: [0 1 2 3 4]
arr[5:]: [5 6 7 8 9]
arr[::2]: [0 2 4 6 8]
arr[::-1]: [9 8 7 6 5 4 3 2 1 0]

First 2 rows:
[[1 2 3 4]
 [5 6 7 8]]
--------------------------------------------------

Last 2 columns:
[[ 3  4]
 [ 7  8]
 [11 12]]
--------------------------------------------------

Center 2x2 block:
[[ 6  7]
 [10 11]]
--------------------------------------------------

Every other element:
[[ 1  3]
 [ 9 11]]
--------------------------------------------------

Train :
 [[1 2 3 4]
 [5 6 7 8]]

Test :
 [[ 9 10 11 12]]


In [24]:
# Reshape 1D to 2D
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print(f"Original: {arr}")
print('--------------------------------------------------\n')
print(f"Reshaped (3x4):\n{reshaped}")
print('--------------------------------------------------\n')

# Reshape with -1 (automatic dimension calculation)
arr = np.arange(24)
auto_reshape = arr.reshape(4, -1)  # NumPy calculates: 24/4 = 6
print(f"Auto reshape (4, -1):\n{auto_reshape}")
print('--------------------------------------------------\n')

# Multiple reshapes
arr = np.arange(24)
reshaped_3d = arr.reshape(2, 3, 4)
print(f"3D reshape (2, 3, 4):\n{reshaped_3d}")
print('--------------------------------------------------\n')

# 3d to 1d
arr_new_1d = reshaped_3d.reshape(24)
print(f"3D -> 1D:\n{arr_new_1d}")
print('--------------------------------------------------\n')

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------------------------------------

Reshaped (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------

Auto reshape (4, -1):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------

3D reshape (2, 3, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------------------------------------

3D -> 1D:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
--------------------------------------------------



### Reshape vs `np.resize` vs `ndarray.resize`

In [20]:
# Reshape: requires compatible dimensions
arr = np.arange(12)
reshaped = np.reshape(arr, (3, 4))  # Works: 12 elements = 3x4
print(f"Reshaped:\n{reshaped}")

# Resize: can change total number of elements
arr = np.arange(6)
resized = np.resize(arr, (3, 4))  # 6 elements -> 12 (repeats pattern)
print(f"\nnp.resize (repeats):\n{resized}")

# ndarray.resize: modifies in place, fills with zeros
arr = np.arange(6)
arr.resize((3, 4))  # Fills extra elements with 0
print(f"\narr.resize (fills with 0):\n{arr}")

Reshaped:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

np.resize (repeats):
[[0 1 2 3]
 [4 5 0 1]
 [2 3 4 5]]

arr.resize (fills with 0):
[[0 1 2 3]
 [4 5 0 0]
 [0 0 0 0]]


### Flattening (`flatten()` and `ravel()`)

In [30]:
# Create 2D array
arr = np.arange(1, 7).reshape(2, 3)
print(f"Original array:\n{arr}")
print('--------------------------------------------------\n')

# flatten: always returns a copy
flattened = arr.flatten()
flattened[0] = 999
print(f"Original after flatten[0]=999:\n{arr}")  # Unchanged

print(f"Flattened: {flattened}")
print('--------------------------------------------------\n')

# ravel: returns view when possible (more memory efficient)
arr = np.arange(1, 7).reshape(3, 2)
print(f"Original array:\n{arr}")

raveled = arr.ravel()
raveled[0] = 999
print(f"Original after ravel[0]=999:\n{arr}")  # Changed!
print('--------------------------------------------------\n')
print(f"Raveled: {raveled}")
print('--------------------------------------------------\n')

# ravel order options
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(f"\nRavel 'C' order (row-major): {arr.ravel()}")
print(f"Ravel 'F' order (column-major): {arr.ravel('F')}")
# arange also supports order options

Original array:
[[1 2 3]
 [4 5 6]]
--------------------------------------------------

Original after flatten[0]=999:
[[1 2 3]
 [4 5 6]]
Flattened: [999   2   3   4   5   6]
--------------------------------------------------

Original array:
[[1 2]
 [3 4]
 [5 6]]
Original after ravel[0]=999:
[[999   2]
 [  3   4]
 [  5   6]]
--------------------------------------------------

Raveled: [999   2   3   4   5   6]
--------------------------------------------------


Ravel 'C' order (row-major): [1 2 3 4 5 6]
Ravel 'F' order (column-major): [1 4 2 5 3 6]


### Transpose and Axis manipulation

In [32]:
# Transpose 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
transposed = arr.T
print(f"Original:\n{arr}")
print('--------------------------------------------------\n')
print(f"Transposed:\n{transposed}")
print('--------------------------------------------------\n')

# Transpose with transpose() method
transposed2 = arr.transpose()
print(f"Using transpose():\n{transposed2}")
print('--------------------------------------------------\n')

# Swapping axes in 3D
arr_3d = np.arange(24).reshape(2, 3, 4)
print(f"3D array :\n{arr_3d}")
print(f"\n3D array shape: {arr_3d.shape}")
print('--------------------------------------------------\n')

swapped = np.swapaxes(arr_3d, 0, 2)  # Swap axis 0 and axis 2
print(f"Swapped array :\n{swapped}")
print(f"\nAfter swapping axes 0 and 2: {swapped.shape}")
print('--------------------------------------------------\n')

# Transpose with specific axis order
transposed_3d = arr_3d.transpose(2, 0, 1)
print(f"Transpose (2,0,1): {transposed_3d.shape}")

Original:
[[1 2 3]
 [4 5 6]]
--------------------------------------------------

Transposed:
[[1 4]
 [2 5]
 [3 6]]
--------------------------------------------------

Using transpose():
[[1 4]
 [2 5]
 [3 6]]
--------------------------------------------------

3D array :
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

3D array shape: (2, 3, 4)
--------------------------------------------------

Swapped array :
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]

After swapping axes 0 and 2: (4, 3, 2)
--------------------------------------------------

Transpose (2,0,1): (4, 2, 3)


### Adding and removing axis

In [33]:
# Add new axis using np.newaxis
arr = np.array([1, 2, 3, 4])
print(f"Original shape: {arr.shape}")

# Add axis at different positions
arr_col = arr[:, np.newaxis]  # Column vector
arr_row = arr[np.newaxis, :]  # Row vector
print(f"Column vector shape: {arr_col.shape}")
print(f"Row vector shape: {arr_row.shape}")

# Using expand_dims
arr_expand = np.expand_dims(arr, axis=0)
print(f"Expand dims axis=0: {arr_expand.shape}")

# Squeeze: remove single-dimensional entries
arr_squeezable = np.array([[[1, 2, 3]]])
print(f"\nBefore squeeze: {arr_squeezable.shape}")
squeezed = np.squeeze(arr_squeezable)
print(f"After squeeze: {squeezed.shape}")
print(f"Squeezed: {squeezed}")

Original shape: (4,)
Column vector shape: (4, 1)
Row vector shape: (1, 4)
Expand dims axis=0: (1, 4)

Before squeeze: (1, 1, 3)
After squeeze: (3,)
Squeezed: [1 2 3]


In [ ]:
a10 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Indexing - masking

print(f'\nAll numbers greater than 4 : {a10[a10 > 4]}')
print(f'\nMask for all numbers less than 3 : {a10 < 3}')
print(f'\nNumbers which are multiple of 2 and 3 : {a10[(a10 % 2 == 0) & (a10 % 3 == 0)]}')
print(f'\nNumbers which are multiple of 2 or 3 : {a10[(a10 % 2 == 0) | (a10 % 3 == 0)]}')
print('---------------------------------------------------------------------')



Row 1 : [1 2 3]

First element : 1

Multiple indexing : 
[[7 8 9]
 [4 5 6]
 [4 5 6]
 [1 2 3]]

Multi dimensional indexing : 
[2 6 8 4]

All numbers greater than 4 : [5 6 7 8 9]

Mask for all numbers less than 3 : [[ True  True False]
 [False False False]
 [False False False]]

Numbers which are multiple of 2 and 3 : [6]

Numbers which are multiple of 2 or 3 : [2 3 4 6 8 9]
---------------------------------------------------------------------
Col 1 :  [1 4 7]

Train :  [[1 2 3]
 [4 5 6]]
Test :  [[7 8 9]]
