<h1 align="center" style="color: orange"> Numpy - III </h1>

In [1]:
import numpy as np

### Random Number Generation

In [2]:
# Set seed for reproducibility
np.random.seed(42)

# Uniform random numbers [0, 1)
uniform = np.random.rand(5)
print(f"Uniform [0,1): {uniform}")

# Uniform in range [low, high)
uniform_range = np.random.uniform(10, 20, size=5)
print(f"Uniform [10,20): {uniform_range}")

# Random integers
integers = np.random.randint(0, 10, size=5)
print(f"Random integers [0,10): {integers}")

# Standard normal distribution (mean=0, std=1)
normal = np.random.randn(5)
print(f"Standard normal: {normal}")

# Normal with specific mean and std
normal_custom = np.random.normal(loc=100, scale=15, size=5)
print(f"Normal (μ=100, σ=15): {normal_custom}")

Uniform [0,1): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Uniform [10,20): [11.5599452  10.58083612 18.66176146 16.01115012 17.08072578]
Random integers [0,10): [5 4 1 7 5]
Standard normal: [ 1.46237812  1.53871497 -2.43910582  0.60344123 -0.25104397]
Normal (μ=100, σ=15): [ 97.54199325  77.8550546  122.30471437  99.63317234 105.33326976]


### Random Sampling

In [3]:
# Random choice from array
data = np.array([10, 20, 30, 40, 50])

# Sample with replacement
sample_with = np.random.choice(data, size=10, replace=True)
print(f"With replacement: {sample_with}")

# Sample without replacement
sample_without = np.random.choice(data, size=3, replace=False)
print(f"Without replacement: {sample_without}")

# Weighted sampling
weights = np.array([0.1, 0.2, 0.3, 0.3, 0.1])
weighted_sample = np.random.choice(data, size=100, p=weights)
print(f"Weighted sample mean: {weighted_sample.mean():.2f}")

With replacement: [50 30 50 10 20 40 10 40 20 20]
Without replacement: [30 40 50]
Weighted sample mean: 30.50


### Random Permutations and Shuffling

In [4]:
# Permutation: return shuffled copy
arr = np.arange(10)
permuted = np.random.permutation(arr)
print(f"Original: {arr}")
print(f"Permuted: {permuted}")

# Shuffle: in-place shuffling
arr_copy = arr.copy()
np.random.shuffle(arr_copy)
print(f"Shuffled: {arr_copy}")

# Shuffle rows of 2D array
matrix = np.arange(12).reshape(3, 4)
print(f"\nOriginal matrix:\n{matrix}")
np.random.shuffle(matrix)
print(f"Shuffled rows:\n{matrix}")

Original: [0 1 2 3 4 5 6 7 8 9]
Permuted: [4 5 8 2 7 6 3 1 9 0]
Shuffled: [6 5 3 4 1 8 2 9 7 0]

Original matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shuffled rows:
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


### Views vs Copies

In [5]:
# View: references same memory
arr = np.arange(10)
view = arr[::2]
view[0] = 999
print(f"Original after view modification: {arr}")

# Check if view
print(f"Is view? {view.base is arr}")

# Copy: independent memory
arr = np.arange(10)
copy = arr[::2].copy()
copy[0] = 999
print(f"Original after copy modification: {arr}")

Original after view modification: [999   1   2   3   4   5   6   7   8   9]
Is view? True
Original after copy modification: [0 1 2 3 4 5 6 7 8 9]


### Structured Arrays

In [6]:
# Define structured dtype
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('score', 'f4')])

# Create structured array
data = np.array([('Alice', 25, 85.5),
                 ('Bob', 30, 92.0),
                 ('Charlie', 28, 78.5)], dtype=dt)

print(f"Structured array:\n{data}")
print(f"\nNames: {data['name']}")
print(f"Ages: {data['age']}")
print(f"Mean score: {data['score'].mean():.2f}")

# Sort by score
sorted_data = np.sort(data, order='score')
print(f"\nSorted by score:\n{sorted_data}")

Structured array:
[('Alice', 25, 85.5) ('Bob', 30, 92. ) ('Charlie', 28, 78.5)]

Names: ['Alice' 'Bob' 'Charlie']
Ages: [25 30 28]
Mean score: 85.33

Sorted by score:
[('Charlie', 28, 78.5) ('Alice', 25, 85.5) ('Bob', 30, 92. )]


### Masked Arrays

In [7]:
# Handle invalid/missing data
data = np.array([1, 2, -999, 4, -999, 6])
masked_data = np.ma.masked_equal(data, -999)

print(f"Masked array: {masked_data}")
print(f"Mean (ignoring masked): {masked_data.mean():.2f}")
print(f"Valid data: {masked_data.compressed()}")

Masked array: [1 2 -- 4 -- 6]
Mean (ignoring masked): 3.25
Valid data: [1 2 4 6]
