<div align="center"> <h1> <font color="Orange"> Numpy - II </font> </h1> </div>

In [1]:
import numpy as np

### Broadcasting

In [6]:
# Example 1: Scalar and array
arr = np.array([1, 2, 3, 4])
result = arr + 10
print(f"Array + scalar: {result}")
# Broadcasting: (4,) + () -> (4,) + (1,) -> (4,)

# Example 2: 1D and 2D
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
result = arr_2d + arr_1d
print(f"\n2D + 1D:\n{result}")
# Broadcasting: (2,3) + (3,) -> (2,3) + (1,3) -> (2,3)

# Example 3: Column and row vectors
col = np.array([[1], [2], [3]])
row = np.array([10, 20, 30, 40])
result = col + row
print(f"\nColumn + row:\n{result}")
# Broadcasting: (3,1) + (4,) -> (3,1) + (1,4) -> (3,4)
# Step-by-step visualization:
# a: (3,1) -> [[1], [2], [3]]
# b: (4,)  -> [10, 20, 30, 40]
# 
# After broadcasting:
# a becomes: [[1, 1, 1, 1],
#             [2, 2, 2, 2],
#             [3, 3, 3, 3]]
# 
# b becomes: [[10, 20, 30, 40],
#             [10, 20, 30, 40],
#             [10, 20, 30, 40]]

# Example 4: Broadcasting in 3D
arr_3d = np.ones((2, 3, 4))
arr_1d = np.array([1, 2, 3, 4])
result = arr_3d + arr_1d
print(f"\n3D shape: {arr_3d.shape}, 1D shape: {arr_1d.shape}")
print(f"Result shape: {result.shape}")
# Broadcasting: (2,3,4) + (4,) -> (2,3,4) + (1,1,4) -> (2,3,4)

Array + scalar: [11 12 13 14]

2D + 1D:
[[11 22 33]
 [14 25 36]]

Column + row:
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]

3D shape: (2, 3, 4), 1D shape: (4,)
Result shape: (2, 3, 4)


In [2]:
# Common pattern: add bias to each sample in batch
batch = np.random.randn(32, 10)  # 32 samples, 10 features
bias = np.random.randn(10)       # 10 biases
result = batch + bias            # Broadcasts correctly
print(f"Batch + bias shape: {result.shape}")

Batch + bias shape: (32, 10)


### Arithmetic UFuncs

In [14]:
# Basic arithmetic operations
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(f"Addition: {np.add(a, b)}")          # a + b
print(f"Subtraction: {np.subtract(a, b)}")  # a - b
print(f"Multiplication: {np.multiply(a, b)}")  # a * b
print(f"Division: {np.divide(b, a)}")       # b / a
print(f"Floor division: {np.floor_divide(b, a)}")  # b // a
print(f"Power: {np.power(a, 2)}")           # a ** 2
print(f"Modulo: {np.mod(b, a)}")            # b % a

# Operator shortcuts
print(f"\nUsing operators:")
print(f"a + b = {a + b}")
print(f"a * 2 = {a * 2}")
print(f"a ** 2 = {a ** 2}")

Addition: [11 22 33 44]
Subtraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Floor division: [10 10 10 10]
Power: [ 1  4  9 16]
Modulo: [0 0 0 0]

Using operators:
a + b = [11 22 33 44]
a * 2 = [2 4 6 8]
a ** 2 = [ 1  4  9 16]


### Comparison UFuncs

In [15]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

print(f"Greater: {np.greater(a, b)}")           # a > b
print(f"Less: {np.less(a, b)}")                 # a < b
print(f"Equal: {np.equal(a, 3)}")               # a == 3
print(f"Not equal: {np.not_equal(a, 3)}")       # a != 3

# Operator shortcuts
print(f"\nUsing operators:")
print(f"a > b: {a > b}")
print(f"a == 3: {a == 3}")

Greater: [False False False  True  True]
Less: [ True  True False False False]
Equal: [False False  True False False]
Not equal: [ True  True False  True  True]

Using operators:
a > b: [False False False  True  True]
a == 3: [False False  True False False]


### Mathematical UFuncs

In [16]:
# Trigonometric functions
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print(f"Sine: {np.sin(angles)}")
print(f"Cosine: {np.cos(angles)}")
print(f"Tangent: {np.tan(angles[:4])}")  # Avoid pi/2 for tan

# Exponential and logarithmic
x = np.array([1, 2, 3, 4, 5])
print(f"\nExponential: {np.exp(x)}")
print(f"Natural log: {np.log(x)}")
print(f"Log base 10: {np.log10(x)}")
print(f"Log base 2: {np.log2(x)}")

# Rounding
x = np.array([1.2, 2.5, 3.7, 4.1, 5.9])
print(f"\nRound: {np.round(x)}")
print(f"Floor: {np.floor(x)}")
print(f"Ceil: {np.ceil(x)}")
print(f"Truncate: {np.trunc(x)}")

Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.         0.57735027 1.         1.73205081]

Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Log base 10: [0.         0.30103    0.47712125 0.60205999 0.69897   ]
Log base 2: [0.         1.         1.5849625  2.         2.32192809]

Round: [1. 2. 4. 4. 6.]
Floor: [1. 2. 3. 4. 5.]
Ceil: [2. 3. 4. 5. 6.]
Truncate: [1. 2. 3. 4. 5.]


### Basic Aggregations

In [18]:
# Create sample data
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print(f"Data:\n{data}\n")

# Aggregate over entire array
print(f"Sum: {np.sum(data)}")
print(f"Mean: {np.mean(data)}")
print(f"Median: {np.median(data)}")
print(f"Standard deviation: {np.std(data)}")
print(f"Variance: {np.var(data)}")
print(f"Min: {np.min(data)}")
print(f"Max: {np.max(data)}")

Data:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sum: 78
Mean: 6.5
Median: 6.5
Standard deviation: 3.452052529534663
Variance: 11.916666666666666
Min: 1
Max: 12


### Axis-Based Operations

In [19]:
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

# Axis 0: down the rows (column-wise operation)
print(f"Sum along axis 0 (column sums): {np.sum(data, axis=0)}")
print(f"Mean along axis 0: {np.mean(data, axis=0)}")

# Axis 1: across the columns (row-wise operation)
print(f"\nSum along axis 1 (row sums): {np.sum(data, axis=1)}")
print(f"Mean along axis 1: {np.mean(data, axis=1)}")

# Multiple axes
data_3d = np.arange(24).reshape(2, 3, 4)
print(f"\n3D data shape: {data_3d.shape}")
print(f"Sum along axes (0, 2): {np.sum(data_3d, axis=(0, 2))}")

Sum along axis 0 (column sums): [15 18 21 24]
Mean along axis 0: [5. 6. 7. 8.]

Sum along axis 1 (row sums): [10 26 42]
Mean along axis 1: [ 2.5  6.5 10.5]

3D data shape: (2, 3, 4)
Sum along axes (0, 2): [ 60  92 124]


### Cumulative Operations

In [3]:
data = np.array([1, 2, 3, 4, 5])

print(f"Data: {data}")
print(f"Cumulative sum: {np.cumsum(data)}")
print(f"Cumulative product: {np.cumprod(data)}")

# 2D cumulative operations
data_2d = np.array([[1, 2, 3],
                    [4, 5, 6]])

print(f"\n2D data:\n{data_2d}")
print(f"\nCumsum axis 0:\n{np.cumsum(data_2d, axis=0)}")
print(f"\nCumsum axis 1:\n{np.cumsum(data_2d, axis=1)}")

Data: [1 2 3 4 5]
Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]

2D data:
[[1 2 3]
 [4 5 6]]

Cumsum axis 0:
[[1 2 3]
 [5 7 9]]

Cumsum axis 1:
[[ 1  3  6]
 [ 4  9 15]]


### ArgMin and ArgMax

In [4]:
# Find indices of min/max values
data = np.array([[23, 17, 31, 14],
                 [89, 12, 65, 43]])

print(f"Data:\n{data}\n")

# Global min/max indices
print(f"Argmin (flattened): {np.argmin(data)}")
print(f"Argmax (flattened): {np.argmax(data)}")
print(f"Min value: {data.flat[np.argmin(data)]}")
print(f"Max value: {data.flat[np.argmax(data)]}")

# Per-axis min/max indices
print(f"\nArgmin axis 0: {np.argmin(data, axis=0)}")
print(f"Argmax axis 0: {np.argmax(data, axis=0)}")
print(f"Argmin axis 1: {np.argmin(data, axis=1)}")
print(f"Argmax axis 1: {np.argmax(data, axis=1)}")

# Convert flat index to 2D coordinates
flat_idx = np.argmax(data)
coords = np.unravel_index(flat_idx, data.shape)
print(f"\nMax value at coordinates: {coords}")

Data:
[[23 17 31 14]
 [89 12 65 43]]

Argmin (flattened): 5
Argmax (flattened): 4
Min value: 12
Max value: 89

Argmin axis 0: [0 1 0 0]
Argmax axis 0: [1 0 1 1]
Argmin axis 1: [3 1]
Argmax axis 1: [2 0]

Max value at coordinates: (np.int64(1), np.int64(0))


### Statistical Functions

In [5]:
# Comprehensive statistics
data = np.array([12, 15, 18, 21, 24, 27, 30, 33, 36])

print(f"Data: {data}\n")
print(f"Mean: {np.mean(data):.2f}")
print(f"Median: {np.median(data):.2f}")
print(f"Standard deviation: {np.std(data):.2f}")
print(f"Variance: {np.var(data):.2f}")

# Percentiles and quantiles
print(f"\n25th percentile: {np.percentile(data, 25):.2f}")
print(f"50th percentile (median): {np.percentile(data, 50):.2f}")
print(f"75th percentile: {np.percentile(data, 75):.2f}")
print(f"90th percentile: {np.percentile(data, 90):.2f}")

# Quantiles (same as percentiles but in [0, 1])
print(f"\nQuartiles: {np.quantile(data, [0.25, 0.5, 0.75])}")

# Range
print(f"\nRange (max - min): {np.ptp(data)}")  # ptp = peak to peak

Data: [12 15 18 21 24 27 30 33 36]

Mean: 24.00
Median: 24.00
Standard deviation: 7.75
Variance: 60.00

25th percentile: 18.00
50th percentile (median): 24.00
75th percentile: 30.00
90th percentile: 33.60

Quartiles: [18. 24. 30.]

Range (max - min): 24


In [2]:
# Weighted average (common in ensemble models)
values = np.array([85, 90, 78, 92])
weights = np.array([0.2, 0.3, 0.1, 0.4])

weighted_avg = np.average(values, weights=weights)
print(f"Values: {values}")
print(f"Weights: {weights}")
print(f"Weighted average: {weighted_avg:.2f}")

# Regular average for comparison
regular_avg = np.mean(values)
print(f"Regular average: {regular_avg:.2f}")

Values: [85 90 78 92]
Weights: [0.2 0.3 0.1 0.4]
Weighted average: 88.60
Regular average: 86.25


### Boolean Aggregations

In [3]:
# Logical operations on boolean arrays
data = np.array([1, 5, 10, 15, 20, 25, 30])

# Check conditions
greater_than_10 = data > 10
print(f"Data > 10: {greater_than_10}")

# Any: True if ANY element is True
print(f"Any > 10? {np.any(data > 10)}")
print(f"Any > 50? {np.any(data > 50)}")

# All: True if ALL elements are True
print(f"All > 0? {np.all(data > 0)}")
print(f"All > 10? {np.all(data > 10)}")

# Count True values
print(f"\nCount > 10: {np.sum(data > 10)}")
print(f"Percentage > 10: {np.mean(data > 10) * 100:.1f}%")

# Find where condition is True
indices = np.where(data > 10)
print(f"Indices where > 10: {indices}")
print(f"Values where > 10: {data[indices]}")

Data > 10: [False False False  True  True  True  True]
Any > 10? True
Any > 50? False
All > 0? True
All > 10? False

Count > 10: 4
Percentage > 10: 57.1%
Indices where > 10: (array([3, 4, 5, 6]),)
Values where > 10: [15 20 25 30]


### Unique and Counting

In [4]:
# Find unique elements
data = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

unique_values = np.unique(data)
print(f"Unique values: {unique_values}")

# Get counts of unique values
unique_vals, counts = np.unique(data, return_counts=True)
print(f"\nValue counts:")
for val, count in zip(unique_vals, counts):
    print(f"  {val}: {count}")

# Get indices of unique values
unique_vals, indices = np.unique(data, return_index=True)
print(f"\nFirst occurrence indices: {indices}")

# Get inverse indices (reconstruct original array)
unique_vals, inverse = np.unique(data, return_inverse=True)
print(f"Inverse indices: {inverse}")
print(f"Reconstructed: {unique_vals[inverse]}")

Unique values: [1 2 3 4]

Value counts:
  1: 1
  2: 2
  3: 3
  4: 4

First occurrence indices: [0 1 3 6]
Inverse indices: [0 1 1 2 2 2 3 3 3 3]
Reconstructed: [1 2 2 3 3 3 4 4 4 4]


### Basic Boolean Indexing

In [5]:
# Create sample data
data = np.array([10, 25, 30, 15, 40, 5, 35, 20])

# Create boolean mask
mask = data > 20
print(f"Data: {data}")
print(f"Mask (data > 20): {mask}")
print(f"Filtered data: {data[mask]}")

# Direct indexing with condition
filtered = data[data > 20]
print(f"Direct filtering: {filtered}")

# Multiple conditions with logical operators
# & (and), | (or), ~ (not)
mask_complex = (data > 15) & (data < 35)
print(f"\nData between 15 and 35: {data[mask_complex]}")

mask_or = (data < 15) | (data > 35)
print(f"Data < 15 OR > 35: {data[mask_or]}")

mask_not = ~(data > 20)
print(f"Data NOT > 20: {data[mask_not]}")

Data: [10 25 30 15 40  5 35 20]
Mask (data > 20): [False  True  True False  True False  True False]
Filtered data: [25 30 40 35]
Direct filtering: [25 30 40 35]

Data between 15 and 35: [25 30 20]
Data < 15 OR > 35: [10 40  5]
Data NOT > 20: [10 15  5 20]


### Boolean Indexing in 2D Arrays

In [6]:
# Student scores: [Math, Physics, Chemistry]
scores = np.array([[85, 78, 92],
                   [67, 88, 73],
                   [92, 84, 89],
                   [74, 69, 81],
                   [88, 91, 95]])

print(f"Scores:\n{scores}\n")

# Find students who scored > 80 in Math (first column)
high_math = scores[:, 0] > 80
print(f"Students with Math > 80:\n{scores[high_math]}")

# Find all scores > 90 (element-wise)
excellent = scores > 90
print(f"\nExcellent scores (>90):\n{scores[excellent]}")

# Count excellent scores per student
excellent_count = np.sum(scores > 90, axis=1)
print(f"\nExcellent scores per student: {excellent_count}")

# Find students with all scores > 75
all_good = np.all(scores > 75, axis=1)
print(f"Students with all scores > 75:\n{scores[all_good]}")

Scores:
[[85 78 92]
 [67 88 73]
 [92 84 89]
 [74 69 81]
 [88 91 95]]

Students with Math > 80:
[[85 78 92]
 [92 84 89]
 [88 91 95]]

Excellent scores (>90):
[92 92 91 95]

Excellent scores per student: [1 0 1 0 2]
Students with all scores > 75:
[[85 78 92]
 [92 84 89]
 [88 91 95]]


### Modifying Values with Boolean Indexing

In [7]:
# Replace values based on condition
data = np.array([10, 25, 30, 15, 40, 5, 35, 20])
print(f"Original: {data}")

# Set all values > 30 to 30 (clipping)
data_copy = data.copy()
data_copy[data_copy > 30] = 30
print(f"Clipped at 30: {data_copy}")

# Increment values that match condition
data_copy = data.copy()
data_copy[data_copy < 20] += 10
print(f"Added 10 to values < 20: {data_copy}")

# Replace with array
data_copy = data.copy()
mask = data_copy > 25
data_copy[mask] = data_copy[mask] * 0.9  # Apply 10% discount
print(f"10% reduction for > 25: {data_copy}")

Original: [10 25 30 15 40  5 35 20]
Clipped at 30: [10 25 30 15 30  5 30 20]
Added 10 to values < 20: [20 25 30 25 40 15 35 20]
10% reduction for > 25: [10 25 27 15 36  5 31 20]


### Using `where` for Conditional Selection

In [8]:
# np.where(condition, value_if_true, value_if_false)
data = np.array([10, 25, 30, 15, 40, 5, 35, 20])

# Replace values: if > 20 then 1, else 0
binary = np.where(data > 20, 1, 0)
print(f"Binary (>20): {binary}")

# Apply different operation based on condition
# If > 25: multiply by 2, else add 5
transformed = np.where(data > 25, data * 2, data + 5)
print(f"Transformed: {transformed}")

# Get indices where condition is True
indices = np.where(data > 25)
print(f"Indices where > 25: {indices[0]}")
print(f"Values where > 25: {data[indices]}")

# 2D example: replace negative values with 0
matrix = np.array([[1, -2, 3],
                   [-4, 5, -6],
                   [7, -8, 9]])
cleaned = np.where(matrix < 0, 0, matrix)
print(f"\nOriginal matrix:\n{matrix}")
print(f"Cleaned matrix:\n{cleaned}")

Binary (>20): [0 1 1 0 1 0 1 0]
Transformed: [15 30 60 20 80 10 70 25]
Indices where > 25: [2 4 6]
Values where > 25: [30 40 35]

Original matrix:
[[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]
Cleaned matrix:
[[1 0 3]
 [0 5 0]
 [7 0 9]]


### Masking for Missing Data

In [9]:
# Simulate dataset with missing values (represented as -999)
data = np.array([[85, 90, -999],
                 [78, -999, 88],
                 [92, 85, 90],
                 [-999, 80, 85]])

print(f"Data with missing values:\n{data}\n")

# Create mask for missing values
missing_mask = data == -999
print(f"Missing mask:\n{missing_mask}\n")

# Replace missing values with column mean
data_clean = data.copy().astype(float)
for col in range(data.shape[1]):
    col_data = data[:, col]
    col_mask = col_data != -999
    col_mean = col_data[col_mask].mean()
    data_clean[data_clean[:, col] == -999, col] = col_mean

print(f"After filling with column means:\n{data_clean}")

# Alternative: use np.ma (masked arrays)
masked_data = np.ma.masked_equal(data, -999)
print(f"\nMasked array:\n{masked_data}")
print(f"Column means (ignoring masked): {masked_data.mean(axis=0)}")

Data with missing values:
[[  85   90 -999]
 [  78 -999   88]
 [  92   85   90]
 [-999   80   85]]

Missing mask:
[[False False  True]
 [False  True False]
 [False False False]
 [ True False False]]

After filling with column means:
[[85.         90.         87.66666667]
 [78.         85.         88.        ]
 [92.         85.         90.        ]
 [85.         80.         85.        ]]

Masked array:
[[85 90 --]
 [78 -- 88]
 [92 85 90]
 [-- 80 85]]
Column means (ignoring masked): [85.0 85.0 87.66666666666667]


### Basic Sorting

In [10]:
# 1D sorting
arr = np.array([5, 2, 8, 1, 9, 3, 7])
sorted_arr = np.sort(arr)
print(f"Original: {arr}")
print(f"Sorted: {sorted_arr}")

# In-place sorting
arr_copy = arr.copy()
arr_copy.sort()
print(f"In-place sorted: {arr_copy}")

# Descending order
desc_sorted = np.sort(arr)[::-1]
print(f"Descending: {desc_sorted}")

Original: [5 2 8 1 9 3 7]
Sorted: [1 2 3 5 7 8 9]
In-place sorted: [1 2 3 5 7 8 9]
Descending: [9 8 7 5 3 2 1]


### Argsort - Sorting Indices

In [11]:
# Get indices that would sort the array
scores = np.array([85, 92, 78, 95, 88])
students = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'])

# Get sorted indices
sorted_indices = np.argsort(scores)
print(f"Scores: {scores}")
print(f"Sorted indices: {sorted_indices}")
print(f"Students (lowest to highest): {students[sorted_indices]}")

# Descending order
desc_indices = np.argsort(scores)[::-1]
print(f"\nTop 3 students: {students[desc_indices[:3]]}")
print(f"Their scores: {scores[desc_indices[:3]]}")

Scores: [85 92 78 95 88]
Sorted indices: [2 0 4 1 3]
Students (lowest to highest): ['Charlie' 'Alice' 'Eve' 'Bob' 'David']

Top 3 students: ['David' 'Bob' 'Eve']
Their scores: [95 92 88]


### Sorting 2D Arrays

In [12]:
# Sort along different axes
data = np.array([[5, 2, 8],
                 [1, 9, 3],
                 [7, 4, 6]])

print(f"Original:\n{data}\n")

# Sort each row
sorted_rows = np.sort(data, axis=1)
print(f"Sorted rows:\n{sorted_rows}\n")

# Sort each column
sorted_cols = np.sort(data, axis=0)
print(f"Sorted columns:\n{sorted_cols}\n")

# Sort rows based on first column
row_order = np.argsort(data[:, 0])
sorted_by_first_col = data[row_order]
print(f"Sorted by first column:\n{sorted_by_first_col}")

Original:
[[5 2 8]
 [1 9 3]
 [7 4 6]]

Sorted rows:
[[2 5 8]
 [1 3 9]
 [4 6 7]]

Sorted columns:
[[1 2 3]
 [5 4 6]
 [7 9 8]]

Sorted by first column:
[[1 9 3]
 [5 2 8]
 [7 4 6]]


### Partitioning - Fast Top-K Selection

In [13]:
# Find top 3 elements (doesn't fully sort)
data = np.array([23, 45, 12, 67, 34, 89, 56, 78])

# Partition: elements < k-th are before, elements >= k-th are after
k = 3
partitioned = np.partition(data, k)
print(f"Original: {data}")
print(f"Partitioned at k={k}: {partitioned}")
print(f"3 smallest: {partitioned[:k]}")  # Not sorted, but all < kth element

# Get top 3 (use negative index for largest)
top_3_partitioned = np.partition(data, -3)
print(f"\nPartitioned for top 3: {top_3_partitioned}")
print(f"Top 3 (unsorted): {top_3_partitioned[-3:]}")

# Get indices with argpartition
indices = np.argpartition(data, -3)[-3:]
top_3_sorted = data[indices[np.argsort(data[indices])[::-1]]]
print(f"Top 3 (sorted): {top_3_sorted}")

Original: [23 45 12 67 34 89 56 78]
Partitioned at k=3: [12 23 34 45 56 67 78 89]
3 smallest: [12 23 34]

Partitioned for top 3: [12 23 34 45 56 67 78 89]
Top 3 (unsorted): [67 78 89]
Top 3 (sorted): [89 78 67]


### Lexicographic Sorting (Multiple Keys)

In [17]:
# Sort by multiple columns
# Data: [Name, Age, Score]
data = np.array([
    ['Alice', 25, 85],
    ['Bob', 30, 92],
    ['Charlie', 25, 78],
    ['David', 30, 88],
    ['Eve', 25, 92]
], dtype=object)

# Sort by Age (ascending), then Score (descending)
# First convert to appropriate types
ages = data[:, 1].astype(int)
scores = data[:, 2].astype(int)

# Use lexsort (sorts by last key first)
indices = np.lexsort((-scores, ages))  # Negative for descending
sorted_data = data[indices]

print("Sorted by Age (asc), then Score (desc):")
for row in sorted_data:
    print(f"{row[0]:8s} Age:{row[1]:2d} Score:{row[2]:2d}")

Sorted by Age (asc), then Score (desc):
Eve      Age:25 Score:92
Alice    Age:25 Score:85
Charlie  Age:25 Score:78
Bob      Age:30 Score:92
David    Age:30 Score:88


### Matrix Multiplication

In [18]:
# Dot product and matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication (modern way)
C = A @ B
print(f"A @ B:\n{C}\n")

# Using np.dot (equivalent for 2D)
C_dot = np.dot(A, B)
print(f"np.dot(A, B):\n{C_dot}\n")

# Matrix-vector multiplication
v = np.array([1, 2])
result = A @ v
print(f"A @ v: {result}")

# Element-wise multiplication (NOT matrix mult)
elementwise = A * B
print(f"\nElement-wise (A * B):\n{elementwise}")

A @ B:
[[19 22]
 [43 50]]

np.dot(A, B):
[[19 22]
 [43 50]]

A @ v: [ 5 11]

Element-wise (A * B):
[[ 5 12]
 [21 32]]


### Common Linear Algebra Operations

In [19]:
# Matrix operations
A = np.array([[1, 2], [3, 4]])

# Transpose
print(f"Transpose:\n{A.T}\n")

# Inverse
A_inv = np.linalg.inv(A)
print(f"Inverse:\n{A_inv}\n")
print(f"A @ A_inv:\n{A @ A_inv}")  # Should be identity

# Determinant
det = np.linalg.det(A)
print(f"\nDeterminant: {det}")

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

# Matrix rank
rank = np.linalg.matrix_rank(A)
print(f"\nRank: {rank}")

# Trace
trace = np.trace(A)
print(f"Trace: {trace}")

Transpose:
[[1 3]
 [2 4]]

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Determinant: -2.0000000000000004
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Rank: 2
Trace: 5
