<h1 align="center" style="color: orange"> Numpy - III </h1>

In [1]:
import numpy as np

### Creating random arrays

In [7]:
# Creating random arrays
rng = np.random.default_rng()

# from normal distribution
a1  = rng.normal(0, 3, size=(3, 4))
print(f'Random array created from normal distribution : {a1}')

# random integers array
a2 = rng.integers(1, 10, size=(3, 4))
print(f'\nRandom array of integers : {a2}')

# random float array
a3 = rng.random((3, 4))
print(f'\nRandom float array : {a3}')

Random array created from normal distribution : [[  0.48237531   0.46751089   3.36755189 -10.08692142]
 [  3.75932795   2.4037292   -3.07912467  -1.55467588]
 [ -0.90832451  -1.76318385  -7.02709351  -5.45104012]]

Random array of integers : [[8 3 1 4]
 [3 2 2 5]
 [2 4 4 7]]

Random float array : [[0.36217262 0.0840522  0.08717386 0.35676831]
 [0.70319107 0.11350849 0.05232433 0.04839408]
 [0.11242347 0.44280192 0.13948498 0.66910179]]


### Memory layout

In [23]:
a4 = a2.view()

print(f'View (original array) of {a4} \nis \n {a4.base}')
print(f'\nView (original array) of {a2} is \n {a2.base}\nNone means this is the original array')
print(f'\na4 and a2 shares memory : {np.shares_memory(a2, a4)}')

a5 = a4[:]
print(f'\na5 and a2 shares memory : {np.shares_memory(a5, a2)}')

a6 = a5[::2]
print(f'\na6 and a2 shares memory : {np.shares_memory(a6, a2)}')

View (original array) of [[8 3 1 4]
 [3 2 2 5]
 [2 4 4 7]] 
is 
 [[8 3 1 4]
 [3 2 2 5]
 [2 4 4 7]]

View (original array) of [[8 3 1 4]
 [3 2 2 5]
 [2 4 4 7]] is 
 None
None means this is the original array

a4 and a2 shares memory : True

a5 and a2 shares memory : True

a6 and a2 shares memory : True


### Tensor and Tensor operations

In [32]:
layers, rows, cols = 2, 4, 3
a7 = np.arange(1, 25).reshape((layers, rows, cols))
print("Tensor : \n", a7)

print(f"\nDimension of the tensor : {a7.ndim}, \nShape of the tensor : {a7.shape}")

Tensor : 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]

Dimension of the tensor : 3, 
Shape of the tensor : (2, 4, 3)


### Masked arrays

In [34]:
print(np.ma.array([1, 2, 3, 4, 5, 6, 7], mask=[1, 0, 1, 1, 1, 1, 0]))

[-- 2 -- -- -- -- 7]


In [36]:
print(np.ma.masked_values([1.0, 1.e20, 3.0, 4.0], 1.e20))

[1.0 -- 3.0 4.0]
