<div align="center"> <h1> <font color="Orange"> Numpy - I </font> </h1> </div>

**$\color{orange}\text{1. Random arrays}$**

There are many builtin ways to create random arrays in numpy.

**$\color{orange}\text{2. Views and Copy}$**

For efficient memory management, NumPy uses views instead of copies whenever possible. This is a very important distinction between NumPy and Python sequences. In contrast, Python always creates new lists when objects are assigned to a new variable name, while numpy shares the same memory space for all variables that refer to the same array.

**$\color{orange}\text{3. Broadcasting}$**

Broadcasting is one of the key features of NumPy that makes it so powerful and easy to use. The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

**$\color{orange}\text{4. Stacking}$**

Stacking is a convenient way to combine multiple arrays into a single array. It is important to note that the dimensions of the input arrays must match, otherwise a ValueError will be raised.

In [1]:
import numpy as np

In [3]:
# Creating random arrays
a = np.random.rand(2, 3)    # random number in uniform distribution
a

array([[0.01037763, 0.47325743, 0.87049912],
       [0.26857958, 0.1685893 , 0.32641222]])

In [4]:
b = np.random.randn(3, 4)   # random numbers in standard normal distribution or Gaussian distribution
b

array([[ 1.16629937,  0.52855748,  0.26604544,  0.86143184],
       [ 0.18098251,  0.46296947, -1.06156923,  0.78169102],
       [ 0.19745402, -0.40826583, -0.22570988, -0.97177169]])

In [5]:
c = np.arange(12).reshape(3, 4)
d = c[::2]

print(f'Array1 is \n{c}\nArray2 is \n{d}\n')
print(np.shares_memory(c,d))

Array1 is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array2 is 
[[ 0  1  2  3]
 [ 8  9 10 11]]

True


In [6]:
# Transcendental functions
e = np.arange(6)
print('Array: \n', e)

print('\nSin array: \n', np.sin(e))
print('\nLog Array: \n', np.log(e[1:]))
print('\nExponent Array: \n', np.exp(e))

Array: 
 [0 1 2 3 4 5]

Sin array: 
 [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

Log Array: 
 [0.         0.69314718 1.09861229 1.38629436 1.60943791]

Exponent Array: 
 [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]


In [8]:
# checking whether an array is a view or original
arr  = np.array([1, 2, 3, 4, 5])
arr2 = arr
arr3 = arr[1:4]
print(arr2.base is None) 
print(arr3.base is None) 

True
False


In [2]:
# structured arrays
x = np.array([(1, 2, 3), (4, 5, 6)], dtype='i8, f4, f8')
x[1] = (7, 8, 9)
x

array([(1, 2., 3.), (7, 8., 9.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

In [14]:
# Create a tensor (3D - 3X4X5)
array0 = np.random.randint(1, 13, size=(3, 4, 5))
print(f'Tensor of 3X4X5 : \n{array0}')

array1 = np.random.randint(1, 13, size=(3, 4))
# array1 = np.array(list(map(int, (np.random.randn(12)*10)))).reshape(3, 4) # ugly way
array2 = np.random.randint(1, 13, size=(4, 4))

Tensor of 3X4X5 : 
[[[ 7  3  9  2  5]
  [ 7  7 10  6 10]
  [ 3  5 11  3  2]
  [ 9 11  5 11 11]]

 [[ 7 10  6  8 10]
  [ 7  3  7 10 11]
  [ 4  7  7  4  3]
  [ 5  2  6  3  6]]

 [[ 2  1  1  8 10]
  [10  5  4  3  3]
  [12  4  5 12 10]
  [11  4  4 11  4]]]


In [26]:
# vertical staking
array3 = np.vstack((array1, array2))
print(f'New array : \n{array3}\n Shape :{array3.shape}, Size : {array3.size}, Dimensions : {array3.ndim}')

New array : 
[[ 6  6  4  9]
 [11  2  1  6]
 [ 9  1  6  4]
 [ 4  1  1  7]
 [ 2  7  1  4]
 [ 3  5  7  4]
 [ 1 10  6  9]]
 Shape :(7, 4), Size : 28, Dimensions : 2


In [28]:
# horizontal stacking
array4 = np.random.randint(1, 13, size=(4, 3))
array5 = np.random.randint(1, 13, size=(4, 5))

array6 = np.hstack((array4, array5))
print(f'New array : \n{array6}\n Shape :{array6.shape}, Size : {array6.size}, Dimensions : {array6.ndim}')

New array : 
[[ 3  1 10 11  8  4  9  2]
 [12  6  8 11  5  9  8  9]
 [10  2 12  5 11  3  1  8]
 [ 3  9  8 10  1  3 12  9]]
 Shape :(4, 8), Size : 32, Dimensions : 2


In [2]:
# a simple image tensor

img_tensor = np.random.randint(0, 256, size=(10, 6, 3))
img_tensor

# curious
# img_tensor = np.random.randint(0, 256, size=(160, 120, 3))
# cv2.imshow('Image', scaled_tensor)
# cv2.imwrite('generated_image.png', scaled_tensor)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

array([[[148, 246, 152],
        [106, 146,  66],
        [ 52,   5,  56],
        [239,  23, 147],
        [  0, 225, 190],
        [238,  48, 255]],

       [[ 62, 228, 166],
        [100, 141,   5],
        [ 33, 103, 252],
        [139,  91,  97],
        [176, 151, 209],
        [ 34,  54,  29]],

       [[204, 174, 220],
        [ 10,  20, 167],
        [144, 106, 226],
        [121, 248,  46],
        [ 52,  27, 235],
        [ 57, 223, 194]],

       [[194, 133, 171],
        [166,  92, 211],
        [ 56,   2, 240],
        [250,  13, 145],
        [ 34, 115, 124],
        [ 42,  22, 188]],

       [[160,  47, 114],
        [144, 170, 167],
        [ 58,  58, 107],
        [ 50, 100, 194],
        [190, 168, 212],
        [ 97,   6,  66]],

       [[ 26,  73, 234],
        [ 59, 197, 240],
        [151, 187,  25],
        [233, 127,  72],
        [ 70, 164,  57],
        [235,   6,  40]],

       [[235, 110, 219],
        [178, 162,  17],
        [ 23,  93,   5],
        [ 20,

In [4]:
another_img_tensor = np.random.randint(256, size=(10, 6, 3))

combined_img_tensor = np.hstack((img_tensor, another_img_tensor))

print(f'Shape : {combined_img_tensor.shape}, Dimension : {combined_img_tensor.ndim}')

Shape : (10, 12, 3), Dimension : 3
