<div align="center"> <h1> <font color="Orange"> Numpy - II </font> </h1> </div>

In [1]:
import numpy as np

### Matrix Operations

In [8]:
# create a matrix of 3, 4
a1 = np.arange(1, 13).reshape((3, 4))
print(f'Matrix : \n{a1}')

# diagonal matrix
diag_matrix = np.diag([1, 2, 3, 4, 5])
print("\nDiagonal Matrix : \n", diag_matrix)
print("\nDiagonal elements are :", np.diag(diag_matrix))

# identity matrix using np.identity() : only square identity matrix
print("\nIdentity matrix : \n", np.identity(5, dtype=int))

# eye() : non square identity matrix
print("\nIdentity matrix : \n", np.eye(3, 4, dtype=int))

Matrix : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Diagonal Matrix : 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

Diagonal elements are : [1 2 3 4 5]

Identity matrix : 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Identity matrix : 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [12]:
# Multiplication
a2 = np.array((1, 2, 3, 4, 5))
a3 = np.array((8, 7, 6, 5, 4))

# multiplication (for 1D with 1D np.dot() is preferred)
a4 = np.dot(a2, a3)
print(f'\nDot product of two 1D arrays : {a4}')

# 1D with a scalar (* is preferred)
print(f'\nTwice of a3 : {a3 * 2}')

# 2D with 2D (np.matmul() or @ is preferred)
a5 = np.arange(1, 13).reshape((3, 4))
a6 = np.arange(12, 24).reshape((4, 3))
a7 = a5 @ a6
a8 = np.matmul(a5, a6)
print(f'\nMultiplication : \n{a7} \n== {a8}')


Dot product of two 1D arrays : 80

Twice of a3 : [16 14 12 10  8]

Multiplication : 
[[180 190 200]
 [444 470 496]
 [708 750 792]] 
== [[180 190 200]
 [444 470 496]
 [708 750 792]]


In [26]:
# any()

print(np.array([1, 2, 3, 4]).any())
print(np.array([1, 0, 3, 0, 0]).any())
print(np.array([0, 0, 0, 0, 0]).any())

True
True
False


In [28]:
# nonzero() : return the indices of elements that are non-zero

print(np.array([1, 2, 3, 0]).nonzero())

(array([0, 1, 2], dtype=int64),)


In [32]:
print(np.array([1, 2, 5]) < np.array([1, 3, 2]))

[False  True False]


In [37]:
# using conditionals with any())
arr_first = np.array([5, 6, 3, 7, 9, 10])
arr_second = np.array([3, 1, 8, 7, 5, 5])

# check if there are any values in the first array such that it is smaller than the value at the same index in the second array.
print(np.any(arr_first < arr_second))

# any value at first array which is double of an element in the second index
print(np.any(arr_first == 2*arr_second))

True
True


In [38]:
# all() checks for all the elements
np.all(arr_first < arr_second)

False

In [39]:
np.all((arr_first <= arr_second) & (arr_second <= arr_first))

False

**`Sorting`**

In [14]:
arr_to_sort = np.random.randint(11, size=10)
print("Array to sort: ", arr_to_sort)

Array to sort:  [10  8  9 10  5  3  2  0  5  9]


In [28]:
np.sort(arr_to_sort)

array([ 0,  2,  3,  5,  5,  8,  9,  9, 10, 10])

- Quick sort (default) : 1.9 µs ± 64.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
- Merge sort : 1.97 µs ± 59.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
- heap sort : 1.92 µs ± 76.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
- Stable sort : 2.01 µs ± 29.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [31]:
arr2D_to_sort = np.random.randint(11, size=(3, 4))

In [42]:
# default sorting is in the last dim; for a matrix it sorts each row { matrix : col wise -> dim0, row wise -> dim1 }
print("Original array:\n", arr2D_to_sort)

Original array:
 [[ 2  4  6  6]
 [10  7 10  9]
 [ 4  2  4  7]]


In [45]:
print(np.sort(arr2D_to_sort, axis=0)) # col wise sort
np.sort(arr2D_to_sort)  # row wise sort

[[ 2  2  4  6]
 [ 4  4  6  7]
 [10  7 10  9]]


array([[ 2,  4,  6,  6],
       [ 7,  9, 10, 10],
       [ 2,  4,  4,  7]])

In [48]:
# argmax : Returns the indices of the maximum values along an axis.
arr23 = np.array([1, 3, 5, 7, 9])
print(np.max(arr23))

np.argmax(arr23)

9


4

In [3]:
# Matrix multiplication
mat1 = np.random.randint(11, size=(3, 4))
mat2 = np.random.randint(11, size=(4, 2))

print(mat1, mat2, sep='\n\n')
np.matmul(mat1, mat2)

[[ 3  1  4  4]
 [ 2  4  4  1]
 [10  9  0  1]]

[[8 1]
 [0 4]
 [1 0]
 [5 6]]


array([[48, 31],
       [25, 24],
       [85, 52]])

In [52]:
mat1 @ mat2 # we can perform matrix multiplication using @ also.

array([[ 82,  66],
       [152, 126],
       [181, 132]])

In [53]:
# mat mul using dot() method
np.dot(mat1, mat2)

array([[ 82,  66],
       [152, 126],
       [181, 132]])