# Coursera ~ Linear Algebra for ML

## Week 1

[Course Link](https://www.coursera.org/learn/machine-learning-linear-algebra)

In [1]:
# importing deps/libraries

import numpy as np

**Introductory Question**

1. Bob has a mixture of apples and oranges of the same size, which he split into two bags. The first bag contains 4 apples and 3 oranges and weighs 700g. The second bag contains 2 apples and 6 oranges and weighs 1000g. 

  Translate the following description into a system of linear equations.

Ans: $4a + 3o = 700$ and $2a + 6o = 1000$

2. Translate the following system of linear equations into the matrix form:

$$5x+3y+5z=6\\7x+2y+8z=17\\4x+3z=8$$

  Ans: $ \begin{bmatrix} 5 & 3 & 5 &\\ 7 & 2 & 8 \\ 0 & 4 & 3 \end{bmatrix} \hspace{1em} \begin{bmatrix}  x\\y\\z \end{bmatrix} \hspace{1em}=\hspace{1em} \begin{bmatrix} 6 \\ 17 \\ 8\end{bmatrix}$



3. Compute the determinant of the following matrix.

```py
  X = [
    [1, 2, 1],
    [0, 3, 5], 
    [4, 3, 8]
  ]
```

In [2]:
x = np.array([
    [1, 2, 1],
    [0, 3, 5], 
    [4, 3, 8]
  ])

det_x = np.linalg.det(x)

print(f'Determinant of the matrix:\n {x} = {det_x:.2f}')

Determinant of the matrix:
 [[1 2 1]
 [0 3 5]
 [4 3 8]] = 37.00


## Determinant of a matrix

Determinant of a matrix is a special value which tells us some important properties of the matrix, like; 

  - If the matrix has inverse or not.
  - Solving systems of linear equations.

**Calculating the determinant of a 2x2 matrix** : $det(X) = ad-bc$ where; 
$$ X= \begin{bmatrix} a & b \\ c & d\end{bmatrix}$$

> For a larger matrix we can find the determinant using a process called Co-factor expansion; which involves choosing a row or column and calculating the determinants of smaller matrices called cofactors. This process can be recursive, meaning you keep calculating determinants of smaller matrices until you reach a 2x2 matrix that you can solve using the formula above

**Note**

- All matrices have a determinant. Only square matrices have determinant. 

- If the determinant is zero, the matrix is said to be singular, and it does not have an inverse.

```py
numpy.linalg.det() 
```

## Slope 

Slope is a measure of how steep a line is. It is defined as the change in the `y-coordinate` (vertical change) divided by the change in the `x-coordinate` (horizontal change) between any two points on the line. 
$$Slope = \frac{rise}{run}$$

**In simple terms it tells us how many units the line moves down for every unit we moves to the right**

### Note

- If a system of linear equations has a unique solution; then they are complete and non-singular.

- If a system of linear equation has infinite solutions; it is redundant and singular.

- if the system of linear equation has no solution; it is called Contradictory and singular.

The constants in the system of equation are not important in determining whether the system is singular or not.

