<h1  style="color:cyan;">

Linear Algebra

</h1>

**Source** : [Course Link](https://www.coursera.org/learn/machine-learning-linear-algebra)

In [1]:
# importing deps/libraries

import numpy as np

<h2  style="color:cyan;">

System of Linear Equations

</h2>

A system of linear equations is a collection of linear equations involving the same set of variables. For example, the following system of linear equations:

$$\begin{align} 2x + 3y &= 8 \\ 3x + 4y &= 9 \end{align}$$ 

is a system of two equations in the variables $x$ and $y$.

A solution to a system of linear equations is a set of values for the variables that satisfies all the equations simultaneously. For example, the values $x = 1$ and $y = 2$ is a solution to the system above.

A system of linear equations can have either no solution, a unique solution or infinitely many solutions. For example, 

- The system of equations:

$$\begin{align} 2x + 3y &= 8 \\ 4x + 6y &= 9 \end{align}$$

has **no solution**. 

- The system of equations:

$$\begin{align} 2x + 3y &= 8 \\ 4x + 6y &= 16 \end{align}$$

has **infinitely many solutions**. 

- The system of equations:

$$\begin{align} 2x + 3y &= 8 \\ 4x + 6y &= 20 \end{align}$$

has a **unique solution**.

<h2  style="color:cyan;">

Matrix Representation of a System of Linear Equations

</h2>

A system of linear equations can be represented in the matrix form as follows:

$$\begin{bmatrix} 2 & 3 \\ 3 & 4 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 8 \\ 9 \end{bmatrix}$$

where the matrix on the left is called the **coefficient matrix** and the matrix on the right is called the **augmented matrix**.


### Questions
1. Bob has a mixture of apples and oranges of the same size, which he split into two bags. The first bag contains 4 apples and 3 oranges and weighs 700g. The second bag contains 2 apples and 6 oranges and weighs 1000g. 

  Translate the following description into a system of linear equations.

**Ans**: $4a + 3o = 700$ and $2a + 6o = 1000$

2. Translate the following system of linear equations into the matrix form:

$$5x+3y+5z=6\\7x+2y+8z=17\\4x+3z=8$$

**Ans**: $ \begin{bmatrix} 5 & 3 & 5 &\\ 7 & 2 & 8 \\ 0 & 4 & 3 \end{bmatrix} \hspace{1em} \begin{bmatrix}  x\\y\\z \end{bmatrix} \hspace{1em}=\hspace{1em} \begin{bmatrix} 6 \\ 17 \\ 8\end{bmatrix}$



3. Compute the determinant of the following matrix.

```py
  X = [
    [1, 2, 1],
    [0, 3, 5], 
    [4, 3, 8]
  ]
```

In [2]:
x = np.array([
    [1, 2, 1],
    [0, 3, 5], 
    [4, 3, 8]
  ])

det_x = np.linalg.det(x)

print(f'Determinant of the matrix:\n {x} = {det_x:.2f}')

Determinant of the matrix:
 [[1 2 1]
 [0 3 5]
 [4 3 8]] = 37.00


<h2  style="color:cyan;">

Determinant of a matrix

</h2>

Determinant of a matrix is a special value which tells us some important properties of the matrix, like; 

  - If the matrix has inverse or not.
  - Solving systems of linear equations.

**Calculating the determinant of a 2x2 matrix** : $det(X) = ad-bc$ where; 
$$ X= \begin{bmatrix} a & b \\ c & d\end{bmatrix}$$

> For a larger matrix we can find the determinant using a process called Co-factor expansion; which involves choosing a row or column and calculating the determinants of smaller matrices called cofactors. This process can be recursive, meaning you keep calculating determinants of smaller matrices until you reach a 2x2 matrix that you can solve using the formula above

**Note**

- All matrices does not have a determinant. Only square matrices have determinant. 

- If the determinant is zero, the matrix is said to be singular, and it does not have an inverse.

```py
numpy.linalg.det() 
```


Consider the following matrix

$$\begin{bmatrix}  a & b \\ c & d\end{bmatrix}$$

The given matrix is singular if $a * b * k$ = $c * d$

or; $$a*k = c \hspace{1em} and \hspace{1em}b*k = d$$

or; $$\frac{c}{a}=\frac{d}{b} = k$$

$$ad = bc$$

$$ad-bc = 0$$ 

This value of $ad-bc = 0$ is important, we call it the determinant of the matrix.


<h2  style="color:cyan;">

Slope 

</h2>

Slope is a measure of how steep a line is. It is defined as the change in the `y-coordinate` (vertical change) divided by the change in the `x-coordinate` (horizontal change) between any two points on the line. 
$$Slope = \frac{rise}{run}$$

**In simple terms it tells us how many units the line moves down for every unit we moves to the right**

### Note

- If a system of linear equations has a unique solution; then they are complete and non-singular.

- If a system of linear equation has infinite solutions; it is redundant and singular.

- if the system of linear equation has no solution; it is called Contradictory and singular.

The constants in the system of equation are not important in determining whether the system is singular or not.

